/**
 * Template set "Hunde-Steckbriefe" (task 12) — the signature feature.
 * Warm, emotional, professional: the dog's photo is the hero. Structured
 * facts (Alter/Rasse/Geschlecht) with fixed captions, character tags line,
 * free-text story, QR to the adoption page.
 */
import type { Palette, Slot, Template } from "../engine/types";
import { FULL_FRAMES, SANS, SERIF } from "./shared";

const DOG_PALETTES: Palette[] = [
  {
    id: "cognac",
    name: "Cognac",
    colors: {
      background: "#f7f0e6",
      surface: "#ffffff",
      accent: "#b06a3b",
      text: "#2c221a",
      textOnAccent: "#fff6ec",
      muted: "#97836f",
    },
  },
  {
    id: "forest",
    name: "Waldgrün",
    colors: {
      background: "#edf1e8",
      surface: "#ffffff",
      accent: "#55704a",
      text: "#222b1e",
      textOnAccent: "#f1f7ec",
      muted: "#7e8a74",
    },
  },
  {
    id: "sky",
    name: "Himmel",
    colors: {
      background: "#e9f0f4",
      surface: "#ffffff",
      accent: "#3e6e8e",
      text: "#1b2831",
      textOnAccent: "#eff7fc",
      muted: "#71838f",
    },
  },
  {
    id: "rosewood",
    name: "Rosenholz",
    colors: {
      background: "#f6ecea",
      surface: "#ffffff",
      accent: "#a85d5d",
      text: "#2e2222",
      textOnAccent: "#fcf1f0",
      muted: "#9a8280",
    },
  },
  {
    id: "mustard",
    name: "Senf",
    colors: {
      background: "#f9f2e2",
      surface: "#ffffff",
      accent: "#a87e23",
      text: "#2d2513",
      textOnAccent: "#fff9ea",
      muted: "#97865c",
    },
  },
];

/** Three structured fact columns (caption + value) for panel layouts. */
function factColumns(opts: {
  color: "text" | "textOnAccent";
  captionColor: "muted" | "textOnAccent";
  captionY: Record<"square" | "portrait" | "story", number>;
  valueY: Record<"square" | "portrait" | "story", number>;
}): Slot[] {
  const columns = [
    { key: "age", caption: "Alter", label: "Alter", example: "3 Jahre", x: 64 },
    {
      key: "breed",
      caption: "Rasse",
      label: "Rasse",
      example: "Mischling",
      x: 381,
    },
    {
      key: "gender",
      caption: "Geschlecht",
      label: "Geschlecht",
      example: "Rüde",
      x: 698,
    },
  ];
  return columns.flatMap((column): Slot[] => [
    {
      id: `${column.key}-caption`,
      type: "text",
      role: "caption",
      label: "",
      fixed: true,
      showWith: column.key,
      font: {
        family: SANS,
        weight: 600,
        minSize: 18,
        maxSize: 21,
        lineHeight: 1.2,
        letterSpacing: 2,
        uppercase: true,
      },
      color: opts.captionColor,
      align: "left",
      vAlign: "bottom",
      maxLines: 1,
      example: column.caption,
      frames: {
        square: { x: column.x, y: opts.captionY.square, w: 280, h: 30 },
        portrait: { x: column.x, y: opts.captionY.portrait, w: 280, h: 30 },
        story: { x: column.x, y: opts.captionY.story, w: 280, h: 34 },
      },
    },
    {
      id: column.key,
      type: "text",
      role: column.key,
      label: column.label,
      optional: true,
      font: {
        family: SANS,
        weight: 700,
        minSize: 24,
        maxSize: 32,
        lineHeight: 1.2,
      },
      color: opts.color,
      align: "left",
      vAlign: "top",
      maxLines: 1,
      maxChars: 18,
      example: column.example,
      frames: {
        square: { x: column.x, y: opts.valueY.square, w: 280, h: 46 },
        portrait: { x: column.x, y: opts.valueY.portrait, w: 280, h: 46 },
        story: { x: column.x, y: opts.valueY.story, w: 280, h: 50 },
      },
    },
  ]);
}

/** Photo top, white panel: the classic Steckbrief. */
const hundSteckbrief: Template = {
  id: "hund-steckbrief",
  name: "Steckbrief",
  category: "dogs",
  palettes: DOG_PALETTES,
  slots: [
    {
      id: "bg",
      type: "background",
      fill: { type: "solid", role: "background" },
      frames: FULL_FRAMES,
    },
    {
      id: "photo",
      type: "photo",
      frames: {
        square: { x: 0, y: 0, w: 1080, h: 560 },
        portrait: { x: 0, y: 0, w: 1080, h: 720 },
        story: { x: 0, y: 0, w: 1080, h: 1040 },
      },
    },
    {
      id: "panel",
      type: "shape",
      shape: "rect",
      fill: { type: "solid", role: "surface" },
      cornerRadius: 48,
      frames: {
        square: { x: 0, y: 520, w: 1080, h: 560 },
        portrait: { x: 0, y: 680, w: 1080, h: 670 },
        story: { x: 0, y: 1000, w: 1080, h: 920 },
      },
    },
    {
      id: "eyebrow",
      type: "text",
      role: "eyebrow",
      label: "",
      fixed: true,
      font: {
        family: SANS,
        weight: 700,
        minSize: 20,
        maxSize: 23,
        lineHeight: 1.2,
        letterSpacing: 4,
        uppercase: true,
      },
      color: "accent",
      align: "left",
      vAlign: "bottom",
      maxLines: 1,
      example: "Ich suche ein Zuhause",
      frames: {
        square: { x: 64, y: 562, w: 850, h: 34 },
        portrait: { x: 64, y: 722, w: 850, h: 34 },
        story: { x: 64, y: 1044, w: 850, h: 38 },
      },
    },
    {
      id: "name",
      type: "text",
      role: "name",
      label: "Name",
      font: {
        family: SERIF,
        weight: 700,
        minSize: 56,
        maxSize: 84,
        lineHeight: 1.05,
      },
      color: "text",
      align: "left",
      vAlign: "top",
      maxLines: 1,
      maxChars: 20,
      example: "Bello",
      frames: {
        square: { x: 64, y: 606, w: 850, h: 108 },
        portrait: { x: 64, y: 766, w: 850, h: 118 },
        story: { x: 64, y: 1090, w: 850, h: 138 },
      },
    },
    ...factColumns({
      color: "text",
      captionColor: "muted",
      captionY: { square: 744, portrait: 914, story: 1258 },
      valueY: { square: 780, portrait: 950, story: 1298 },
    }),
    {
      id: "traits",
      type: "text",
      role: "traits",
      label: "Charakter (z. B. verspielt · lieb)",
      optional: true,
      font: {
        family: SANS,
        weight: 600,
        minSize: 24,
        maxSize: 29,
        lineHeight: 1.3,
      },
      color: "accent",
      align: "left",
      vAlign: "center",
      maxLines: 1,
      maxChars: 50,
      example: "verspielt · kinderlieb · leinenführig",
      frames: {
        square: { x: 64, y: 848, w: 850, h: 42 },
        portrait: { x: 64, y: 1020, w: 850, h: 42 },
        story: { x: 64, y: 1372, w: 850, h: 46 },
      },
    },
    {
      id: "story",
      type: "text",
      role: "story",
      label: "Über mich",
      optional: true,
      multiline: true,
      font: {
        family: SANS,
        weight: 400,
        minSize: 22,
        maxSize: 27,
        lineHeight: 1.42,
      },
      color: "muted",
      align: "left",
      vAlign: "top",
      maxLines: 4,
      maxChars: 220,
      example:
        "Ich bin ein fröhlicher Kerl, der Menschen liebt und gern Neues lernt. Ein Garten wäre mein großer Traum!",
      frames: {
        square: { x: 64, y: 910, w: 700, h: 150 },
        portrait: { x: 64, y: 1082, w: 700, h: 190 },
        story: { x: 64, y: 1440, w: 690, h: 300 },
      },
    },
    {
      id: "qr",
      type: "qr",
      optional: true,
      frames: {
        square: { x: 866, y: 906, w: 120, h: 120 },
        portrait: { x: 866, y: 1082, w: 120, h: 120 },
        story: { x: 850, y: 1460, w: 140, h: 140 },
      },
    },
    {
      id: "qr-caption",
      type: "text",
      role: "caption",
      label: "",
      fixed: true,
      showWith: "qr",
      font: {
        family: SANS,
        weight: 600,
        minSize: 17,
        maxSize: 19,
        lineHeight: 1.25,
      },
      color: "muted",
      align: "center",
      vAlign: "top",
      maxLines: 1,
      example: "Lern mich kennen!",
      frames: {
        square: { x: 816, y: 1032, w: 220, h: 28 },
        portrait: { x: 816, y: 1208, w: 220, h: 28 },
        story: { x: 800, y: 1606, w: 240, h: 32 },
      },
    },
    {
      id: "logo",
      type: "logo",
      optional: true,
      guardrails: {
        maxOffsetX: 40,
        maxOffsetY: 40,
        minScale: 0.8,
        maxScale: 1.2,
      },
      frames: {
        square: { x: 48, y: 48, w: 120, h: 120 },
        portrait: { x: 48, y: 48, w: 120, h: 120 },
        story: { x: 48, y: 64, w: 140, h: 140 },
      },
    },
  ],
};

/** Full-bleed photo, name over a warm scrim: the Herzensbrecher. */
const hundVollbild: Template = {
  id: "hund-vollbild",
  name: "Herzensbrecher",
  category: "dogs",
  palettes: DOG_PALETTES,
  slots: [
    { id: "photo", type: "photo", frames: FULL_FRAMES },
    {
      id: "scrim",
      type: "shape",
      shape: "rect",
      fill: { type: "scrim", role: "text", direction: "down", opacity: 0.9 },
      frames: {
        square: { x: 0, y: 500, w: 1080, h: 580 },
        portrait: { x: 0, y: 700, w: 1080, h: 650 },
        story: { x: 0, y: 1150, w: 1080, h: 770 },
      },
    },
    {
      id: "eyebrow",
      type: "text",
      role: "eyebrow",
      label: "Kleine Zeile oben",
      optional: true,
      font: {
        family: SANS,
        weight: 700,
        minSize: 22,
        maxSize: 26,
        lineHeight: 1.2,
        letterSpacing: 3,
        uppercase: true,
      },
      color: "textOnAccent",
      align: "left",
      vAlign: "center",
      maxLines: 1,
      maxChars: 28,
      badge: {
        fill: { type: "solid", role: "accent" },
        paddingX: 24,
        paddingY: 14,
        cornerRadius: 999,
      },
      example: "Ich suche ein Zuhause",
      guardrails: {
        maxOffsetX: 50,
        maxOffsetY: 40,
        minScale: 0.85,
        maxScale: 1.2,
      },
      frames: {
        square: { x: 88, y: 78, w: 560, h: 52 },
        portrait: { x: 88, y: 88, w: 560, h: 52 },
        story: { x: 88, y: 140, w: 580, h: 56 },
      },
    },
    {
      id: "name",
      type: "text",
      role: "name",
      label: "Name",
      font: {
        family: SERIF,
        weight: 700,
        minSize: 72,
        maxSize: 112,
        lineHeight: 1,
      },
      color: "background",
      align: "left",
      vAlign: "bottom",
      maxLines: 1,
      maxChars: 18,
      example: "Bello",
      frames: {
        square: { x: 64, y: 700, w: 850, h: 150 },
        portrait: { x: 64, y: 950, w: 850, h: 170 },
        story: { x: 64, y: 1450, w: 850, h: 190 },
      },
    },
    {
      id: "facts",
      type: "text",
      role: "facts",
      label: "Kurzinfo (z. B. Alter · Rasse)",
      optional: true,
      font: {
        family: SANS,
        weight: 500,
        minSize: 26,
        maxSize: 33,
        lineHeight: 1.3,
      },
      color: "background",
      align: "left",
      vAlign: "top",
      maxLines: 1,
      maxChars: 45,
      example: "3 Jahre · Mischling · Rüde",
      frames: {
        square: { x: 64, y: 872, w: 800, h: 48 },
        portrait: { x: 64, y: 1142, w: 800, h: 48 },
        story: { x: 64, y: 1662, w: 800, h: 52 },
      },
    },
    {
      id: "qr",
      type: "qr",
      optional: true,
      frames: {
        square: { x: 920, y: 924, w: 96, h: 96 },
        portrait: { x: 920, y: 1194, w: 96, h: 96 },
        story: { x: 900, y: 1744, w: 120, h: 120 },
      },
    },
    {
      id: "logo",
      type: "logo",
      optional: true,
      guardrails: {
        maxOffsetX: 40,
        maxOffsetY: 40,
        minScale: 0.8,
        maxScale: 1.2,
      },
      frames: {
        square: { x: 912, y: 64, w: 110, h: 110 },
        portrait: { x: 912, y: 76, w: 110, h: 110 },
        story: { x: 892, y: 140, w: 130, h: 130 },
      },
    },
  ],
};

/** Trading-card look: photo and story on one generous white card. */
const hundKarte: Template = {
  id: "hund-karte",
  name: "Sammelkarte",
  category: "dogs",
  palettes: DOG_PALETTES,
  slots: [
    {
      id: "bg",
      type: "background",
      fill: { type: "solid", role: "background" },
      frames: FULL_FRAMES,
    },
    {
      id: "card",
      type: "shape",
      shape: "rect",
      fill: { type: "solid", role: "surface" },
      cornerRadius: 40,
      frames: {
        square: { x: 64, y: 64, w: 952, h: 952 },
        portrait: { x: 64, y: 64, w: 952, h: 1222 },
        story: { x: 64, y: 96, w: 952, h: 1728 },
      },
    },
    {
      id: "photo",
      type: "photo",
      cornerRadius: 24,
      frames: {
        square: { x: 104, y: 104, w: 872, h: 500 },
        portrait: { x: 104, y: 104, w: 872, h: 680 },
        story: { x: 104, y: 136, w: 872, h: 1080 },
      },
    },
    {
      id: "name",
      type: "text",
      role: "name",
      label: "Name",
      font: {
        family: SERIF,
        weight: 650,
        minSize: 52,
        maxSize: 76,
        lineHeight: 1.05,
      },
      color: "text",
      align: "center",
      vAlign: "center",
      maxLines: 1,
      maxChars: 20,
      example: "Luna",
      frames: {
        square: { x: 144, y: 636, w: 792, h: 96 },
        portrait: { x: 144, y: 820, w: 792, h: 104 },
        story: { x: 144, y: 1252, w: 792, h: 124 },
      },
    },
    {
      id: "facts",
      type: "text",
      role: "facts",
      label: "Kurzinfo (z. B. Alter · Rasse)",
      optional: true,
      font: {
        family: SANS,
        weight: 600,
        minSize: 24,
        maxSize: 30,
        lineHeight: 1.3,
      },
      color: "accent",
      align: "center",
      vAlign: "center",
      maxLines: 1,
      maxChars: 45,
      example: "2 Jahre · Podenco-Mix · Hündin",
      frames: {
        square: { x: 144, y: 744, w: 792, h: 42 },
        portrait: { x: 144, y: 936, w: 792, h: 44 },
        story: { x: 144, y: 1388, w: 792, h: 48 },
      },
    },
    {
      id: "story",
      type: "text",
      role: "story",
      label: "Über mich",
      optional: true,
      multiline: true,
      font: {
        family: SANS,
        weight: 400,
        minSize: 22,
        maxSize: 27,
        lineHeight: 1.45,
      },
      color: "muted",
      align: "center",
      vAlign: "top",
      maxLines: 4,
      maxChars: 220,
      example:
        "Ich bin anfangs etwas schüchtern – aber wer mein Herz gewinnt, hat eine Freundin fürs Leben.",
      frames: {
        square: { x: 144, y: 806, w: 792, h: 170 },
        portrait: { x: 144, y: 1000, w: 792, h: 230 },
        story: { x: 144, y: 1456, w: 792, h: 300 },
      },
    },
    {
      id: "logo",
      type: "logo",
      optional: true,
      guardrails: {
        maxOffsetX: 40,
        maxOffsetY: 40,
        minScale: 0.8,
        maxScale: 1.2,
      },
      frames: {
        square: { x: 880, y: 128, w: 110, h: 110 },
        portrait: { x: 880, y: 128, w: 110, h: 110 },
        story: { x: 860, y: 168, w: 130, h: 130 },
      },
    },
  ],
};

/** Photo top, warm accent panel with structured facts. */
const hundBanner: Template = {
  id: "hund-banner",
  name: "Warmherz",
  category: "dogs",
  palettes: DOG_PALETTES,
  slots: [
    {
      id: "photo",
      type: "photo",
      frames: {
        square: { x: 0, y: 0, w: 1080, h: 600 },
        portrait: { x: 0, y: 0, w: 1080, h: 780 },
        story: { x: 0, y: 0, w: 1080, h: 1120 },
      },
    },
    {
      id: "panel",
      type: "shape",
      shape: "rect",
      fill: { type: "solid", role: "accent" },
      cornerRadius: 48,
      frames: {
        square: { x: 0, y: 560, w: 1080, h: 520 },
        portrait: { x: 0, y: 740, w: 1080, h: 610 },
        story: { x: 0, y: 1080, w: 1080, h: 840 },
      },
    },
    {
      id: "eyebrow",
      type: "text",
      role: "eyebrow",
      label: "",
      fixed: true,
      font: {
        family: SANS,
        weight: 700,
        minSize: 19,
        maxSize: 22,
        lineHeight: 1.2,
        letterSpacing: 5,
        uppercase: true,
      },
      color: "textOnAccent",
      align: "left",
      vAlign: "bottom",
      maxLines: 1,
      example: "Steckbrief",
      frames: {
        square: { x: 64, y: 604, w: 850, h: 32 },
        portrait: { x: 64, y: 784, w: 850, h: 32 },
        story: { x: 64, y: 1124, w: 850, h: 36 },
      },
    },
    {
      id: "name",
      type: "text",
      role: "name",
      label: "Name",
      font: {
        family: SERIF,
        weight: 700,
        minSize: 56,
        maxSize: 84,
        lineHeight: 1.05,
      },
      color: "textOnAccent",
      align: "left",
      vAlign: "top",
      maxLines: 1,
      maxChars: 20,
      example: "Rocky",
      frames: {
        square: { x: 64, y: 646, w: 850, h: 108 },
        portrait: { x: 64, y: 826, w: 850, h: 118 },
        story: { x: 64, y: 1170, w: 850, h: 138 },
      },
    },
    ...factColumns({
      color: "textOnAccent",
      captionColor: "textOnAccent",
      captionY: { square: 784, portrait: 964, story: 1338 },
      valueY: { square: 820, portrait: 1000, story: 1378 },
    }),
    {
      id: "story",
      type: "text",
      role: "story",
      label: "Über mich",
      optional: true,
      multiline: true,
      font: {
        family: SANS,
        weight: 400,
        minSize: 22,
        maxSize: 26,
        lineHeight: 1.42,
      },
      color: "textOnAccent",
      align: "left",
      vAlign: "top",
      maxLines: 4,
      maxChars: 200,
      example:
        "Ein Senior mit Herz: Ich liebe gemütliche Spaziergänge und ausgiebige Streicheleinheiten.",
      frames: {
        square: { x: 64, y: 888, w: 700, h: 150 },
        portrait: { x: 64, y: 1070, w: 700, h: 190 },
        story: { x: 64, y: 1450, w: 690, h: 290 },
      },
    },
    {
      id: "qr",
      type: "qr",
      optional: true,
      cornerRadius: 16,
      frames: {
        square: { x: 866, y: 890, w: 120, h: 120 },
        portrait: { x: 866, y: 1072, w: 120, h: 120 },
        story: { x: 850, y: 1460, w: 140, h: 140 },
      },
    },
    {
      id: "qr-caption",
      type: "text",
      role: "caption",
      label: "",
      fixed: true,
      showWith: "qr",
      font: {
        family: SANS,
        weight: 600,
        minSize: 17,
        maxSize: 19,
        lineHeight: 1.25,
      },
      color: "textOnAccent",
      align: "center",
      vAlign: "top",
      maxLines: 1,
      example: "Scan mich!",
      frames: {
        square: { x: 816, y: 1016, w: 220, h: 28 },
        portrait: { x: 816, y: 1198, w: 220, h: 28 },
        story: { x: 800, y: 1606, w: 240, h: 32 },
      },
    },
    {
      id: "logo",
      type: "logo",
      optional: true,
      guardrails: {
        maxOffsetX: 40,
        maxOffsetY: 40,
        minScale: 0.8,
        maxScale: 1.2,
      },
      frames: {
        square: { x: 48, y: 48, w: 120, h: 120 },
        portrait: { x: 48, y: 48, w: 120, h: 120 },
        story: { x: 48, y: 64, w: 140, h: 140 },
      },
    },
  ],
};

export const dogTemplates: Template[] = [
  hundSteckbrief,
  hundVollbild,
  hundKarte,
  hundBanner,
];
