/**
 * Template set "Produkte & Angebote" (task 10): four clean, commercial
 * layouts in all three formats, five curated palettes.
 */
import type { Palette, Template } from "../engine/types";
import {
  BADGE_RAILS,
  FULL_FRAMES,
  LOGO_RAILS,
  QR_RAILS,
  SANS,
  SERIF,
  TEXT_RAILS,
} from "./shared";

const PRODUCT_PALETTES: Palette[] = [
  {
    id: "terracotta",
    name: "Terrakotta",
    colors: {
      background: "#f6efe7",
      surface: "#ffffff",
      accent: "#c4633c",
      text: "#2b2118",
      textOnAccent: "#fff7f0",
      muted: "#94826e",
    },
  },
  {
    id: "sage",
    name: "Salbei",
    colors: {
      background: "#eef1ea",
      surface: "#ffffff",
      accent: "#4e6b51",
      text: "#1f2921",
      textOnAccent: "#f2f7f0",
      muted: "#7c8877",
    },
  },
  {
    id: "night",
    name: "Nachtblau",
    colors: {
      background: "#e8edf5",
      surface: "#ffffff",
      accent: "#23405f",
      text: "#16202e",
      textOnAccent: "#eef4fb",
      muted: "#6c7a8c",
    },
  },
  {
    id: "honey",
    name: "Honig",
    colors: {
      background: "#fbf3e2",
      surface: "#ffffff",
      accent: "#a87718",
      text: "#2e2410",
      textOnAccent: "#fff9ec",
      muted: "#96854f",
    },
  },
  {
    id: "berry",
    name: "Beere",
    colors: {
      background: "#f5ebf0",
      surface: "#ffffff",
      accent: "#8e3b62",
      text: "#2b1b24",
      textOnAccent: "#fbeff5",
      muted: "#8d7583",
    },
  },
  {
    id: "weihnachten",
    name: "Weihnachten",
    colors: {
      background: "#f7efe6",
      surface: "#ffffff",
      accent: "#9e2b2b",
      text: "#2d1c18",
      textOnAccent: "#fdf3ec",
      muted: "#97806f",
    },
  },
  {
    id: "sommer",
    name: "Sommer",
    colors: {
      background: "#eaf4f2",
      surface: "#ffffff",
      accent: "#e0763a",
      text: "#23302e",
      textOnAccent: "#fff4ea",
      muted: "#74908a",
    },
  },
  {
    id: "edel",
    name: "Schwarz & Gold",
    colors: {
      background: "#232019",
      surface: "#2e2a21",
      accent: "#d4af5a",
      text: "#f1ece0",
      textOnAccent: "#2b2210",
      muted: "#a49a86",
    },
  },
];

/** Photo top, white panel with headline / description / price. */
const produktKlassik: Template = {
  id: "produkt-klassik",
  name: "Klassik",
  category: "products",
  palettes: PRODUCT_PALETTES,
  variants: [
    { id: "weich", name: "Abgerundet", overrides: {} },
    { id: "kantig", name: "Kantig", overrides: { panel: { cornerRadius: 0 } } },
  ],
  slots: [
    {
      id: "bg",
      type: "background",
      fill: { type: "solid", role: "background" },
      frames: FULL_FRAMES,
    },
    {
      id: "photo",
      type: "photo",
      frames: {
        square: { x: 0, y: 0, w: 1080, h: 600 },
        portrait: { x: 0, y: 0, w: 1080, h: 800 },
        story: { x: 0, y: 0, w: 1080, h: 1080 },
      },
    },
    {
      id: "panel",
      type: "shape",
      shape: "rect",
      fill: { type: "solid", role: "surface" },
      cornerRadius: 48,
      frames: {
        square: { x: 0, y: 560, w: 1080, h: 520 },
        portrait: { x: 0, y: 760, w: 1080, h: 590 },
        story: { x: 0, y: 1040, w: 1080, h: 880 },
      },
    },
    {
      id: "headline",
      type: "text",
      role: "headline",
      label: "Überschrift",
      font: {
        family: SANS,
        weight: 700,
        minSize: 44,
        maxSize: 72,
        lineHeight: 1.12,
      },
      color: "text",
      align: "left",
      vAlign: "bottom",
      maxLines: 2,
      maxChars: 60,
      example: "Frisch gebackenes Sauerteigbrot",
      guardrails: TEXT_RAILS,
      frames: {
        square: { x: 64, y: 620, w: 952, h: 170 },
        portrait: { x: 64, y: 820, w: 952, h: 180 },
        story: { x: 64, y: 1110, w: 952, h: 220 },
      },
    },
    {
      id: "description",
      type: "text",
      role: "description",
      label: "Beschreibung",
      multiline: true,
      font: {
        family: SANS,
        weight: 400,
        minSize: 24,
        maxSize: 32,
        lineHeight: 1.4,
      },
      color: "muted",
      align: "left",
      vAlign: "top",
      maxLines: 3,
      maxChars: 140,
      example:
        "Jeden Samstag ab 8 Uhr im Hofladen – solange der Vorrat reicht.",
      guardrails: TEXT_RAILS,
      frames: {
        square: { x: 64, y: 830, w: 600, h: 150 },
        portrait: { x: 64, y: 1040, w: 620, h: 170 },
        story: { x: 64, y: 1370, w: 700, h: 220 },
      },
    },
    {
      id: "price",
      type: "text",
      role: "price",
      label: "Preis",
      font: {
        family: SANS,
        weight: 800,
        minSize: 32,
        maxSize: 48,
        lineHeight: 1.1,
      },
      color: "textOnAccent",
      align: "center",
      vAlign: "center",
      maxLines: 1,
      maxChars: 12,
      badge: {
        fill: { type: "solid", role: "accent" },
        paddingX: 36,
        paddingY: 20,
        cornerRadius: 999,
      },
      example: "4,50 €",
      guardrails: BADGE_RAILS,
      frames: {
        square: { x: 740, y: 830, w: 276, h: 110 },
        portrait: { x: 740, y: 1040, w: 276, h: 110 },
        story: { x: 720, y: 1370, w: 296, h: 120 },
      },
    },
    {
      id: "qr",
      type: "qr",
      optional: true,
      guardrails: QR_RAILS,
      frames: {
        square: { x: 920, y: 952, w: 96, h: 96 },
        portrait: { x: 920, y: 1192, w: 96, h: 96 },
        story: { x: 900, y: 1680, w: 120, h: 120 },
      },
    },
    {
      id: "logo",
      type: "logo",
      optional: true,
      guardrails: LOGO_RAILS,
      frames: {
        square: { x: 48, y: 48, w: 120, h: 120 },
        portrait: { x: 48, y: 48, w: 120, h: 120 },
        story: { x: 48, y: 64, w: 140, h: 140 },
      },
    },
  ],
};

/** Full-bleed photo with dark scrim and bold headline over it. */
const produktVollbild: Template = {
  id: "produkt-vollbild",
  name: "Vollbild",
  category: "products",
  palettes: PRODUCT_PALETTES,
  variants: [
    { id: "kraeftig", name: "Kräftiger Verlauf", overrides: {} },
    {
      id: "dezent",
      name: "Dezenter Verlauf",
      overrides: {
        scrim: {
          fill: {
            type: "scrim",
            role: "text",
            direction: "down",
            opacity: 0.55,
          },
        },
      },
    },
  ],
  slots: [
    { id: "photo", type: "photo", frames: FULL_FRAMES },
    {
      id: "scrim",
      type: "shape",
      shape: "rect",
      fill: { type: "scrim", role: "text", direction: "down", opacity: 0.88 },
      frames: {
        square: { x: 0, y: 400, w: 1080, h: 680 },
        portrait: { x: 0, y: 560, w: 1080, h: 790 },
        story: { x: 0, y: 940, w: 1080, h: 980 },
      },
    },
    {
      id: "eyebrow",
      type: "text",
      role: "eyebrow",
      label: "Kleine Zeile oben",
      optional: true,
      font: {
        family: SANS,
        weight: 600,
        minSize: 24,
        maxSize: 30,
        lineHeight: 1.2,
        letterSpacing: 4,
        uppercase: true,
      },
      color: "background",
      align: "left",
      vAlign: "bottom",
      maxLines: 1,
      maxChars: 30,
      example: "Angebot der Woche",
      guardrails: TEXT_RAILS,
      frames: {
        square: { x: 64, y: 560, w: 850, h: 44 },
        portrait: { x: 64, y: 790, w: 850, h: 44 },
        story: { x: 64, y: 1200, w: 850, h: 48 },
      },
    },
    {
      id: "headline",
      type: "text",
      role: "headline",
      label: "Überschrift",
      font: {
        family: SANS,
        weight: 800,
        minSize: 52,
        maxSize: 84,
        lineHeight: 1.08,
      },
      color: "background",
      align: "left",
      vAlign: "top",
      maxLines: 3,
      maxChars: 70,
      example: "Handgemachte Keramik",
      guardrails: TEXT_RAILS,
      frames: {
        square: { x: 64, y: 620, w: 800, h: 260 },
        portrait: { x: 64, y: 850, w: 820, h: 280 },
        story: { x: 64, y: 1264, w: 860, h: 320 },
      },
    },
    {
      id: "price",
      type: "text",
      role: "price",
      label: "Preis",
      optional: true,
      font: {
        family: SANS,
        weight: 800,
        minSize: 30,
        maxSize: 44,
        lineHeight: 1.1,
      },
      color: "textOnAccent",
      align: "center",
      vAlign: "center",
      maxLines: 1,
      maxChars: 14,
      badge: {
        fill: { type: "solid", role: "accent" },
        paddingX: 32,
        paddingY: 18,
        cornerRadius: 999,
      },
      example: "ab 24 €",
      guardrails: BADGE_RAILS,
      frames: {
        square: { x: 64, y: 920, w: 250, h: 100 },
        portrait: { x: 64, y: 1170, w: 250, h: 100 },
        story: { x: 64, y: 1640, w: 270, h: 110 },
      },
    },
    {
      id: "qr",
      type: "qr",
      optional: true,
      guardrails: QR_RAILS,
      frames: {
        square: { x: 920, y: 920, w: 100, h: 100 },
        portrait: { x: 920, y: 1180, w: 100, h: 100 },
        story: { x: 900, y: 1680, w: 120, h: 120 },
      },
    },
    {
      id: "logo",
      type: "logo",
      optional: true,
      guardrails: LOGO_RAILS,
      frames: {
        square: { x: 48, y: 48, w: 120, h: 120 },
        portrait: { x: 48, y: 48, w: 120, h: 120 },
        story: { x: 48, y: 64, w: 140, h: 140 },
      },
    },
  ],
};

/** Gallery look: photo in a generous passe-partout, centered serif title. */
const produktRahmen: Template = {
  id: "produkt-rahmen",
  name: "Galerie",
  category: "products",
  palettes: PRODUCT_PALETTES,
  variants: [
    { id: "galerie", name: "Klassisch", overrides: {} },
    {
      id: "rund",
      name: "Runde Ecken",
      overrides: { photo: { cornerRadius: 48 } },
    },
  ],
  slots: [
    {
      id: "bg",
      type: "background",
      fill: { type: "solid", role: "surface" },
      frames: FULL_FRAMES,
    },
    {
      id: "photo",
      type: "photo",
      cornerRadius: 8,
      frames: {
        square: { x: 64, y: 64, w: 952, h: 620 },
        portrait: { x: 64, y: 64, w: 952, h: 840 },
        story: { x: 64, y: 96, w: 952, h: 1180 },
      },
    },
    {
      id: "eyebrow",
      type: "text",
      role: "eyebrow",
      label: "Kleine Zeile",
      optional: true,
      font: {
        family: SANS,
        weight: 600,
        minSize: 22,
        maxSize: 26,
        lineHeight: 1.2,
        letterSpacing: 5,
        uppercase: true,
      },
      color: "accent",
      align: "center",
      vAlign: "center",
      maxLines: 1,
      maxChars: 30,
      example: "Neu eingetroffen",
      guardrails: TEXT_RAILS,
      frames: {
        square: { x: 104, y: 726, w: 872, h: 40 },
        portrait: { x: 104, y: 950, w: 872, h: 40 },
        story: { x: 104, y: 1330, w: 872, h: 44 },
      },
    },
    {
      id: "headline",
      type: "text",
      role: "headline",
      label: "Titel",
      font: {
        family: SERIF,
        weight: 600,
        minSize: 42,
        maxSize: 64,
        lineHeight: 1.15,
      },
      color: "text",
      align: "center",
      vAlign: "top",
      maxLines: 2,
      maxChars: 50,
      example: "Vase „Landliebe“",
      guardrails: TEXT_RAILS,
      frames: {
        square: { x: 104, y: 780, w: 872, h: 150 },
        portrait: { x: 104, y: 1004, w: 872, h: 160 },
        story: { x: 104, y: 1390, w: 872, h: 190 },
      },
    },
    {
      id: "price",
      type: "text",
      role: "price",
      label: "Preis",
      optional: true,
      font: {
        family: SANS,
        weight: 700,
        minSize: 28,
        maxSize: 38,
        lineHeight: 1.2,
      },
      color: "accent",
      align: "center",
      vAlign: "top",
      maxLines: 1,
      maxChars: 14,
      example: "39 €",
      guardrails: BADGE_RAILS,
      frames: {
        square: { x: 340, y: 940, w: 400, h: 56 },
        portrait: { x: 340, y: 1170, w: 400, h: 56 },
        story: { x: 340, y: 1590, w: 400, h: 64 },
      },
    },
    {
      id: "description",
      type: "text",
      role: "description",
      label: "Beschreibung",
      optional: true,
      multiline: true,
      font: {
        family: SANS,
        weight: 400,
        minSize: 22,
        maxSize: 26,
        lineHeight: 1.45,
      },
      color: "muted",
      align: "center",
      vAlign: "top",
      maxLines: 2,
      maxChars: 100,
      example:
        "Jedes Stück ein Unikat – gedreht und glasiert in unserer Werkstatt.",
      guardrails: TEXT_RAILS,
      frames: {
        square: { x: 144, y: 1004, w: 792, h: 70 },
        portrait: { x: 144, y: 1234, w: 792, h: 80 },
        story: { x: 144, y: 1670, w: 792, h: 90 },
      },
    },
  ],
};

/** Color block: accent top with headline, photo below, price on the photo. */
const produktFarbblock: Template = {
  id: "produkt-farbblock",
  name: "Farbblock",
  category: "products",
  palettes: PRODUCT_PALETTES,
  variants: [
    { id: "weich", name: "Abgerundet", overrides: {} },
    { id: "kantig", name: "Kantig", overrides: { photo: { cornerRadius: 0 } } },
  ],
  slots: [
    {
      id: "bg",
      type: "background",
      fill: { type: "solid", role: "accent" },
      frames: FULL_FRAMES,
    },
    {
      id: "headline",
      type: "text",
      role: "headline",
      label: "Überschrift",
      font: {
        family: SANS,
        weight: 800,
        minSize: 44,
        maxSize: 70,
        lineHeight: 1.1,
      },
      color: "textOnAccent",
      align: "left",
      vAlign: "center",
      maxLines: 2,
      maxChars: 55,
      example: "Wochenend-Rabatt: 20 % auf alles",
      guardrails: TEXT_RAILS,
      frames: {
        square: { x: 64, y: 88, w: 780, h: 230 },
        portrait: { x: 64, y: 104, w: 780, h: 270 },
        story: { x: 64, y: 150, w: 800, h: 330 },
      },
    },
    {
      id: "description",
      type: "text",
      role: "description",
      label: "Beschreibung",
      optional: true,
      font: {
        family: SANS,
        weight: 500,
        minSize: 24,
        maxSize: 30,
        lineHeight: 1.35,
      },
      color: "textOnAccent",
      align: "left",
      vAlign: "top",
      maxLines: 2,
      maxChars: 90,
      example: "Nur Samstag und Sonntag – im Laden und online.",
      guardrails: TEXT_RAILS,
      frames: {
        square: { x: 64, y: 336, w: 850, h: 84 },
        portrait: { x: 64, y: 396, w: 850, h: 90 },
        story: { x: 64, y: 500, w: 880, h: 100 },
      },
    },
    {
      id: "photo",
      type: "photo",
      cornerRadius: 32,
      frames: {
        square: { x: 64, y: 460, w: 952, h: 556 },
        portrait: { x: 64, y: 540, w: 952, h: 746 },
        story: { x: 64, y: 680, w: 952, h: 1176 },
      },
    },
    {
      id: "price",
      type: "text",
      role: "price",
      label: "Preis / Code",
      optional: true,
      font: {
        family: SANS,
        weight: 800,
        minSize: 28,
        maxSize: 40,
        lineHeight: 1.1,
      },
      color: "text",
      align: "center",
      vAlign: "center",
      maxLines: 1,
      maxChars: 16,
      badge: {
        fill: { type: "solid", role: "surface" },
        paddingX: 30,
        paddingY: 18,
        cornerRadius: 20,
      },
      example: "Code: WOCHENENDE",
      guardrails: BADGE_RAILS,
      frames: {
        square: { x: 620, y: 510, w: 350, h: 96 },
        portrait: { x: 620, y: 590, w: 350, h: 96 },
        story: { x: 600, y: 730, w: 370, h: 106 },
      },
    },
    {
      id: "qr",
      type: "qr",
      optional: true,
      cornerRadius: 16,
      guardrails: QR_RAILS,
      frames: {
        square: { x: 112, y: 872, w: 100, h: 100 },
        portrait: { x: 112, y: 1142, w: 100, h: 100 },
        story: { x: 112, y: 1712, w: 120, h: 120 },
      },
    },
    {
      id: "logo",
      type: "logo",
      optional: true,
      guardrails: LOGO_RAILS,
      frames: {
        square: { x: 896, y: 96, w: 120, h: 120 },
        portrait: { x: 896, y: 112, w: 120, h: 120 },
        story: { x: 876, y: 160, w: 140, h: 140 },
      },
    },
  ],
};

export const productTemplates: Template[] = [
  produktKlassik,
  produktVollbild,
  produktRahmen,
  produktFarbblock,
];
