/**
 * Template set "Zitate, Tipps & Infoposts" (task 11): four text-first
 * layouts that look finished without any photo. Typography does the work:
 * Fraunces for the statement, Outfit for structure.
 */
import type { Palette, Template } from "../engine/types";
import {
  BADGE_RAILS,
  FULL_FRAMES,
  LOGO_RAILS,
  QR_RAILS,
  SANS,
  SERIF,
  TEXT_RAILS,
} from "./shared";

const QUOTE_PALETTES: Palette[] = [
  {
    id: "cream",
    name: "Creme",
    colors: {
      background: "#f6f1e9",
      surface: "#ffffff",
      accent: "#bc5b33",
      text: "#2a241c",
      textOnAccent: "#fff6ef",
      muted: "#98897a",
    },
  },
  {
    id: "sage",
    name: "Salbei",
    colors: {
      background: "#e9eee6",
      surface: "#f9fbf7",
      accent: "#47664b",
      text: "#1e2a21",
      textOnAccent: "#f0f6ee",
      muted: "#78857a",
    },
  },
  {
    id: "ink",
    name: "Tinte (dunkel)",
    colors: {
      background: "#232733",
      surface: "#2d3240",
      accent: "#e3b04e",
      text: "#f0ede5",
      textOnAccent: "#2a2109",
      muted: "#9ba0ad",
    },
  },
  {
    id: "powder",
    name: "Puder",
    colors: {
      background: "#f6e9e7",
      surface: "#ffffff",
      accent: "#b04a5a",
      text: "#2e2126",
      textOnAccent: "#fdf1f3",
      muted: "#a08186",
    },
  },
  {
    id: "ocean",
    name: "Ozean",
    colors: {
      background: "#e6eef0",
      surface: "#f8fbfc",
      accent: "#20586b",
      text: "#14262c",
      textOnAccent: "#eaf4f7",
      muted: "#6b838c",
    },
  },
  {
    id: "weihnachten",
    name: "Weihnachten",
    colors: {
      background: "#f5ece4",
      surface: "#ffffff",
      accent: "#8f2f2f",
      text: "#2c1b16",
      textOnAccent: "#fcf1ea",
      muted: "#97806f",
    },
  },
  {
    id: "flieder",
    name: "Flieder",
    colors: {
      background: "#efeaf5",
      surface: "#faf8fd",
      accent: "#6b5397",
      text: "#262033",
      textOnAccent: "#f3eefb",
      muted: "#8d84a0",
    },
  },
];

/** Big centered serif quote with a decorative mark and author line. */
const zitatKlassisch: Template = {
  id: "zitat-klassisch",
  name: "Zitat",
  category: "quotes",
  palettes: QUOTE_PALETTES,
  variants: [
    { id: "klassisch", name: "Mit Zeichen", overrides: {} },
    { id: "pur", name: "Pur", overrides: { mark: { hidden: true } } },
  ],
  slots: [
    {
      id: "bg",
      type: "background",
      fill: { type: "solid", role: "background" },
      frames: FULL_FRAMES,
    },
    {
      id: "mark",
      type: "text",
      role: "decoration",
      label: "",
      fixed: true,
      font: {
        family: SERIF,
        weight: 900,
        minSize: 140,
        maxSize: 180,
        lineHeight: 1,
      },
      color: "accent",
      align: "center",
      vAlign: "center",
      maxLines: 1,
      example: "„",
      frames: {
        square: { x: 440, y: 96, w: 200, h: 170 },
        portrait: { x: 440, y: 140, w: 200, h: 190 },
        story: { x: 440, y: 260, w: 200, h: 210 },
      },
    },
    {
      id: "quote",
      type: "text",
      role: "quote",
      label: "Zitat oder Gedanke",
      multiline: true,
      font: {
        family: SERIF,
        weight: 500,
        minSize: 40,
        maxSize: 68,
        lineHeight: 1.25,
      },
      color: "text",
      align: "center",
      vAlign: "center",
      maxLines: 6,
      maxChars: 220,
      example:
        "Das Glück ist das einzige, das sich verdoppelt, wenn man es teilt.",
      guardrails: TEXT_RAILS,
      frames: {
        square: { x: 104, y: 290, w: 872, h: 440 },
        portrait: { x: 104, y: 370, w: 872, h: 540 },
        story: { x: 104, y: 520, w: 872, h: 740 },
      },
    },
    {
      id: "rule",
      type: "shape",
      shape: "rect",
      fill: { type: "solid", role: "accent" },
      cornerRadius: 3,
      frames: {
        square: { x: 505, y: 780, w: 70, h: 6 },
        portrait: { x: 505, y: 960, w: 70, h: 6 },
        story: { x: 505, y: 1320, w: 70, h: 6 },
      },
    },
    {
      id: "author",
      type: "text",
      role: "author",
      label: "Von wem? (optional)",
      optional: true,
      font: {
        family: SANS,
        weight: 600,
        minSize: 22,
        maxSize: 28,
        lineHeight: 1.3,
        letterSpacing: 3,
        uppercase: true,
      },
      color: "muted",
      align: "center",
      vAlign: "top",
      maxLines: 1,
      maxChars: 40,
      example: "Albert Schweitzer",
      guardrails: TEXT_RAILS,
      frames: {
        square: { x: 190, y: 822, w: 700, h: 44 },
        portrait: { x: 190, y: 1002, w: 700, h: 44 },
        story: { x: 190, y: 1362, w: 700, h: 48 },
      },
    },
    {
      id: "logo",
      type: "logo",
      optional: true,
      guardrails: LOGO_RAILS,
      frames: {
        square: { x: 490, y: 930, w: 100, h: 100 },
        portrait: { x: 490, y: 1150, w: 100, h: 100 },
        story: { x: 480, y: 1600, w: 120, h: 120 },
      },
    },
  ],
};

/** Tip card: surface card with small badge line, headline, and body text. */
const tippKarte: Template = {
  id: "tipp-karte",
  name: "Tipp-Karte",
  category: "quotes",
  palettes: QUOTE_PALETTES,
  variants: [
    { id: "weich", name: "Abgerundet", overrides: {} },
    { id: "kantig", name: "Kantig", overrides: { card: { cornerRadius: 0 } } },
  ],
  slots: [
    {
      id: "bg",
      type: "background",
      fill: { type: "solid", role: "background" },
      frames: FULL_FRAMES,
    },
    {
      id: "card",
      type: "shape",
      shape: "rect",
      fill: { type: "solid", role: "surface" },
      cornerRadius: 40,
      frames: {
        square: { x: 64, y: 120, w: 952, h: 840 },
        portrait: { x: 64, y: 140, w: 952, h: 1070 },
        story: { x: 64, y: 240, w: 952, h: 1440 },
      },
    },
    {
      id: "eyebrow",
      type: "text",
      role: "eyebrow",
      label: "Kleine Zeile (z. B. Tipp 1)",
      font: {
        family: SANS,
        weight: 700,
        minSize: 22,
        maxSize: 26,
        lineHeight: 1.2,
        letterSpacing: 3,
        uppercase: true,
      },
      color: "textOnAccent",
      align: "left",
      vAlign: "center",
      maxLines: 1,
      maxChars: 24,
      badge: {
        fill: { type: "solid", role: "accent" },
        paddingX: 26,
        paddingY: 14,
        cornerRadius: 999,
      },
      example: "Tipp des Tages",
      guardrails: BADGE_RAILS,
      frames: {
        square: { x: 154, y: 190, w: 500, h: 50 },
        portrait: { x: 154, y: 214, w: 500, h: 50 },
        story: { x: 154, y: 320, w: 500, h: 54 },
      },
    },
    {
      id: "headline",
      type: "text",
      role: "headline",
      label: "Überschrift",
      font: {
        family: SANS,
        weight: 700,
        minSize: 34,
        maxSize: 52,
        lineHeight: 1.18,
      },
      color: "text",
      align: "left",
      vAlign: "top",
      maxLines: 3,
      maxChars: 80,
      example: "So bleibt dein Brot länger frisch",
      guardrails: TEXT_RAILS,
      frames: {
        square: { x: 128, y: 290, w: 824, h: 190 },
        portrait: { x: 128, y: 320, w: 824, h: 210 },
        story: { x: 128, y: 430, w: 824, h: 250 },
      },
    },
    {
      id: "body",
      type: "text",
      role: "body",
      label: "Dein Text",
      multiline: true,
      font: {
        family: SANS,
        weight: 400,
        minSize: 26,
        maxSize: 32,
        lineHeight: 1.45,
      },
      color: "muted",
      align: "left",
      vAlign: "top",
      maxLines: 7,
      maxChars: 320,
      example:
        "Bewahre Brot nie im Kühlschrank auf – dort wird es schneller alt. Ein Brotkasten aus Ton oder ein Leinenbeutel hält die Kruste knusprig und die Krume saftig.",
      guardrails: TEXT_RAILS,
      frames: {
        square: { x: 128, y: 500, w: 824, h: 300 },
        portrait: { x: 128, y: 550, w: 824, h: 480 },
        story: { x: 128, y: 700, w: 824, h: 700 },
      },
    },
    {
      id: "qr",
      type: "qr",
      optional: true,
      guardrails: QR_RAILS,
      frames: {
        square: { x: 856, y: 832, w: 96, h: 96 },
        portrait: { x: 856, y: 1082, w: 96, h: 96 },
        story: { x: 832, y: 1528, w: 120, h: 120 },
      },
    },
    {
      id: "logo",
      type: "logo",
      optional: true,
      guardrails: LOGO_RAILS,
      frames: {
        square: { x: 128, y: 840, w: 90, h: 90 },
        portrait: { x: 128, y: 1090, w: 90, h: 90 },
        story: { x: 128, y: 1540, w: 110, h: 110 },
      },
    },
  ],
};

/** Bold fact on a full accent background. */
const wusstestDu: Template = {
  id: "wusstest-du",
  name: "Wusstest du?",
  category: "quotes",
  palettes: QUOTE_PALETTES,
  variants: [
    { id: "flaeche", name: "Einfarbig", overrides: {} },
    {
      id: "verlauf",
      name: "Verlauf",
      overrides: {
        bg: {
          fill: {
            type: "linear-gradient",
            from: "accent",
            to: "text",
            angle: 24,
          },
        },
      },
    },
  ],
  slots: [
    {
      id: "bg",
      type: "background",
      fill: { type: "solid", role: "accent" },
      frames: FULL_FRAMES,
    },
    {
      id: "eyebrow",
      type: "text",
      role: "eyebrow",
      label: "Kleine Zeile oben",
      font: {
        family: SANS,
        weight: 700,
        minSize: 24,
        maxSize: 30,
        lineHeight: 1.2,
        letterSpacing: 4,
        uppercase: true,
      },
      color: "textOnAccent",
      align: "center",
      vAlign: "center",
      maxLines: 1,
      maxChars: 26,
      example: "Wusstest du?",
      guardrails: TEXT_RAILS,
      frames: {
        square: { x: 140, y: 140, w: 800, h: 44 },
        portrait: { x: 140, y: 180, w: 800, h: 44 },
        story: { x: 140, y: 310, w: 800, h: 48 },
      },
    },
    {
      id: "fact",
      type: "text",
      role: "quote",
      label: "Dein Fakt",
      multiline: true,
      font: {
        family: SERIF,
        weight: 550,
        minSize: 44,
        maxSize: 76,
        lineHeight: 1.2,
      },
      color: "textOnAccent",
      align: "center",
      vAlign: "center",
      maxLines: 6,
      maxChars: 180,
      example: "Hunde können rund 250 Wörter und Gesten verstehen.",
      guardrails: TEXT_RAILS,
      frames: {
        square: { x: 104, y: 250, w: 872, h: 540 },
        portrait: { x: 104, y: 310, w: 872, h: 680 },
        story: { x: 104, y: 490, w: 872, h: 880 },
      },
    },
    {
      id: "subline",
      type: "text",
      role: "author",
      label: "Quelle oder Zusatz (optional)",
      optional: true,
      font: {
        family: SANS,
        weight: 500,
        minSize: 22,
        maxSize: 26,
        lineHeight: 1.35,
      },
      color: "textOnAccent",
      align: "center",
      vAlign: "top",
      maxLines: 2,
      maxChars: 80,
      example: "Quelle: Studie der Uni Wien",
      guardrails: TEXT_RAILS,
      frames: {
        square: { x: 190, y: 830, w: 700, h: 70 },
        portrait: { x: 190, y: 1040, w: 700, h: 70 },
        story: { x: 190, y: 1430, w: 700, h: 80 },
      },
    },
    {
      id: "logo",
      type: "logo",
      optional: true,
      guardrails: LOGO_RAILS,
      frames: {
        square: { x: 490, y: 930, w: 100, h: 100 },
        portrait: { x: 490, y: 1160, w: 100, h: 100 },
        story: { x: 480, y: 1610, w: 120, h: 120 },
      },
    },
  ],
};

/** Announcement: centered headline, date badge, details, QR. */
const ankuendigung: Template = {
  id: "ankuendigung",
  name: "Ankündigung",
  category: "quotes",
  palettes: QUOTE_PALETTES,
  variants: [
    { id: "hell", name: "Zarter Grund", overrides: {} },
    {
      id: "weiss",
      name: "Weißer Grund",
      overrides: { bg: { fill: { type: "solid", role: "surface" } } },
    },
  ],
  slots: [
    {
      id: "bg",
      type: "background",
      fill: { type: "solid", role: "background" },
      frames: FULL_FRAMES,
    },
    {
      id: "logo",
      type: "logo",
      optional: true,
      guardrails: LOGO_RAILS,
      frames: {
        square: { x: 490, y: 72, w: 100, h: 100 },
        portrait: { x: 490, y: 96, w: 100, h: 100 },
        story: { x: 480, y: 170, w: 120, h: 120 },
      },
    },
    {
      id: "eyebrow",
      type: "text",
      role: "eyebrow",
      label: "Kleine Zeile oben",
      optional: true,
      font: {
        family: SANS,
        weight: 700,
        minSize: 22,
        maxSize: 28,
        lineHeight: 1.2,
        letterSpacing: 4,
        uppercase: true,
      },
      color: "accent",
      align: "center",
      vAlign: "center",
      maxLines: 1,
      maxChars: 30,
      example: "Nicht verpassen",
      guardrails: TEXT_RAILS,
      frames: {
        square: { x: 140, y: 214, w: 800, h: 40 },
        portrait: { x: 140, y: 260, w: 800, h: 40 },
        story: { x: 140, y: 400, w: 800, h: 44 },
      },
    },
    {
      id: "headline",
      type: "text",
      role: "headline",
      label: "Was steht an?",
      multiline: true,
      font: {
        family: SERIF,
        weight: 600,
        minSize: 46,
        maxSize: 70,
        lineHeight: 1.15,
      },
      color: "text",
      align: "center",
      vAlign: "center",
      maxLines: 3,
      maxChars: 90,
      example: "Tag der offenen Tür im Tierheim",
      guardrails: TEXT_RAILS,
      frames: {
        square: { x: 84, y: 280, w: 912, h: 250 },
        portrait: { x: 84, y: 340, w: 912, h: 290 },
        story: { x: 84, y: 500, w: 912, h: 350 },
      },
    },
    {
      id: "datebadge",
      type: "text",
      role: "date",
      label: "Wann & wo?",
      font: {
        family: SANS,
        weight: 700,
        minSize: 26,
        maxSize: 36,
        lineHeight: 1.15,
      },
      color: "textOnAccent",
      align: "center",
      vAlign: "center",
      maxLines: 1,
      maxChars: 40,
      badge: {
        fill: { type: "solid", role: "accent" },
        paddingX: 34,
        paddingY: 18,
        cornerRadius: 999,
      },
      example: "So., 14. Juni · 11–17 Uhr",
      guardrails: BADGE_RAILS,
      frames: {
        square: { x: 240, y: 570, w: 600, h: 90 },
        portrait: { x: 240, y: 680, w: 600, h: 90 },
        story: { x: 220, y: 900, w: 640, h: 100 },
      },
    },
    {
      id: "description",
      type: "text",
      role: "description",
      label: "Details (optional)",
      optional: true,
      multiline: true,
      font: {
        family: SANS,
        weight: 400,
        minSize: 24,
        maxSize: 30,
        lineHeight: 1.45,
      },
      color: "muted",
      align: "center",
      vAlign: "top",
      maxLines: 3,
      maxChars: 140,
      example:
        "Mit Führungen, Kuchen und ganz vielen Fellnasen, die dich kennenlernen möchten.",
      guardrails: TEXT_RAILS,
      frames: {
        square: { x: 144, y: 700, w: 792, h: 140 },
        portrait: { x: 144, y: 820, w: 792, h: 170 },
        story: { x: 144, y: 1070, w: 792, h: 220 },
      },
    },
    {
      id: "qr",
      type: "qr",
      optional: true,
      guardrails: QR_RAILS,
      frames: {
        square: { x: 492, y: 880, w: 96, h: 96 },
        portrait: { x: 492, y: 1050, w: 96, h: 96 },
        story: { x: 480, y: 1380, w: 120, h: 120 },
      },
    },
  ],
};

export const quoteTemplates: Template[] = [
  zitatKlassisch,
  tippKarte,
  wusstestDu,
  ankuendigung,
];
