/**
 * The single-image templates.
 *
 * Every editable text slot carries one of the four universal content ids
 * (`title1`, `text1`, `title2`, `text2`, see engine/types.ts), so the content
 * the user typed before picking a template shows up in all of them. Slots with
 * other ids (the `dog:*` fields of the Steckbrief) are template extras and are
 * offered as additional fields once that template is chosen.
 *
 * Reading of the four fields, everywhere:
 *   title1 — the headline            text1 — the main paragraph
 *   title2 — short second heading    text2 — the secondary line
 */
import type { LogoSlot, QrSlot, Slot, Template } from "../engine/types";
import { PALETTES } from "./palettes";
import {
  FULL_FRAMES,
  LOGO_RAILS,
  PHOTO_RAILS,
  QR_RAILS,
  SANS,
  SERIF,
  TEXT_RAILS,
} from "./shared";

type Frames = Slot["frames"];

function qr(frames: Frames, cornerRadius?: number): QrSlot {
  return {
    id: "qr",
    type: "qr",
    optional: true,
    cornerRadius,
    guardrails: QR_RAILS,
    frames,
  };
}

function logo(frames: Frames): LogoSlot {
  return {
    id: "logo",
    type: "logo",
    optional: true,
    guardrails: LOGO_RAILS,
    frames,
  };
}

/* ------------------------------------------------------------------ Klassik */

/** Photo on top, white panel with headline, text and a highlight chip. */
const klassik: Template = {
  id: "klassik",
  name: "Klassik",
  hint: "Foto oben, Text auf weißer Karte",
  palettes: PALETTES,
  variants: [
    { id: "weich", name: "Abgerundet", overrides: {} },
    { id: "kantig", name: "Kantig", overrides: { panel: { cornerRadius: 0 } } },
  ],
  slots: [
    {
      id: "bg",
      type: "background",
      fill: { type: "solid", role: "background" },
      frames: FULL_FRAMES,
    },
    {
      id: "photo",
      type: "photo",
      guardrails: PHOTO_RAILS,
      frames: {
        square: { x: 0, y: 0, w: 1080, h: 600 },
        portrait: { x: 0, y: 0, w: 1080, h: 800 },
        story: { x: 0, y: 0, w: 1080, h: 1080 },
      },
    },
    {
      id: "panel",
      type: "shape",
      shape: "rect",
      fill: { type: "solid", role: "surface" },
      cornerRadius: 48,
      frames: {
        square: { x: 0, y: 560, w: 1080, h: 520 },
        portrait: { x: 0, y: 760, w: 1080, h: 590 },
        story: { x: 0, y: 1040, w: 1080, h: 880 },
      },
    },
    {
      id: "title1",
      type: "text",
      role: "headline",
      label: "Überschrift 1",
      font: {
        family: SANS,
        weight: 700,
        minSize: 44,
        maxSize: 72,
        lineHeight: 1.12,
      },
      color: "text",
      align: "left",
      vAlign: "bottom",
      maxLines: 2,
      maxChars: 60,
      example: "Frisch gebackenes Sauerteigbrot",
      guardrails: TEXT_RAILS,
      frames: {
        square: { x: 64, y: 620, w: 952, h: 170 },
        portrait: { x: 64, y: 820, w: 952, h: 180 },
        story: { x: 64, y: 1110, w: 952, h: 220 },
      },
    },
    {
      id: "text1",
      type: "text",
      role: "description",
      label: "Beschreibungstext 1",
      optional: true,
      multiline: true,
      font: {
        family: SANS,
        weight: 400,
        minSize: 24,
        maxSize: 32,
        lineHeight: 1.4,
      },
      color: "muted",
      align: "left",
      vAlign: "top",
      maxLines: 3,
      maxChars: 140,
      example:
        "Jeden Samstag ab 8 Uhr im Hofladen – solange der Vorrat reicht.",
      guardrails: TEXT_RAILS,
      frames: {
        square: { x: 64, y: 830, w: 600, h: 150 },
        portrait: { x: 64, y: 1040, w: 620, h: 170 },
        story: { x: 64, y: 1370, w: 700, h: 220 },
      },
    },
    {
      id: "title2",
      type: "text",
      role: "highlight",
      label: "Überschrift 2",
      optional: true,
      font: {
        family: SANS,
        weight: 800,
        minSize: 32,
        maxSize: 48,
        lineHeight: 1.1,
      },
      color: "textOnAccent",
      align: "center",
      vAlign: "center",
      maxLines: 1,
      maxChars: 14,
      badge: {
        fill: { type: "solid", role: "accent" },
        paddingX: 36,
        paddingY: 20,
        cornerRadius: 999,
      },
      example: "4,50 €",
      guardrails: TEXT_RAILS,
      frames: {
        square: { x: 740, y: 830, w: 276, h: 110 },
        portrait: { x: 740, y: 1040, w: 276, h: 110 },
        story: { x: 720, y: 1370, w: 296, h: 120 },
      },
    },
    {
      id: "text2",
      type: "text",
      role: "note",
      label: "Beschreibungstext 2",
      optional: true,
      font: {
        family: SANS,
        weight: 500,
        minSize: 20,
        maxSize: 26,
        lineHeight: 1.3,
      },
      color: "muted",
      align: "left",
      vAlign: "center",
      maxLines: 1,
      maxChars: 60,
      example: "Bestellungen gern vorab per Nachricht",
      guardrails: TEXT_RAILS,
      frames: {
        square: { x: 64, y: 996, w: 780, h: 44 },
        portrait: { x: 64, y: 1226, w: 780, h: 44 },
        story: { x: 64, y: 1610, w: 780, h: 50 },
      },
    },
    qr({
      square: { x: 920, y: 952, w: 96, h: 96 },
      portrait: { x: 920, y: 1192, w: 96, h: 96 },
      story: { x: 900, y: 1680, w: 120, h: 120 },
    }),
    logo({
      square: { x: 48, y: 48, w: 120, h: 120 },
      portrait: { x: 48, y: 48, w: 120, h: 120 },
      story: { x: 48, y: 64, w: 140, h: 140 },
    }),
  ],
};

/* ----------------------------------------------------------------- Vollbild */

/** Full-bleed photo with a scrim and bold text over it. */
const vollbild: Template = {
  id: "vollbild",
  name: "Vollbild",
  hint: "Foto über das ganze Bild, Text darauf",
  palettes: PALETTES,
  variants: [
    { id: "kraeftig", name: "Kräftiger Verlauf", overrides: {} },
    {
      id: "dezent",
      name: "Dezenter Verlauf",
      overrides: {
        scrim: {
          fill: {
            type: "scrim",
            role: "text",
            direction: "down",
            opacity: 0.55,
          },
        },
      },
    },
  ],
  slots: [
    {
      id: "photo",
      type: "photo",
      guardrails: PHOTO_RAILS,
      frames: FULL_FRAMES,
    },
    {
      id: "scrim",
      type: "shape",
      shape: "rect",
      fill: { type: "scrim", role: "text", direction: "down", opacity: 0.88 },
      frames: {
        square: { x: 0, y: 400, w: 1080, h: 680 },
        portrait: { x: 0, y: 560, w: 1080, h: 790 },
        story: { x: 0, y: 940, w: 1080, h: 980 },
      },
    },
    {
      id: "title2",
      type: "text",
      role: "highlight",
      label: "Überschrift 2",
      optional: true,
      font: {
        family: SANS,
        weight: 800,
        minSize: 26,
        maxSize: 40,
        lineHeight: 1.1,
      },
      color: "textOnAccent",
      align: "center",
      vAlign: "center",
      maxLines: 1,
      maxChars: 16,
      badge: {
        fill: { type: "solid", role: "accent" },
        paddingX: 32,
        paddingY: 18,
        cornerRadius: 999,
      },
      example: "ab 24 €",
      guardrails: TEXT_RAILS,
      frames: {
        square: { x: 64, y: 540, w: 320, h: 86 },
        portrait: { x: 64, y: 760, w: 320, h: 86 },
        story: { x: 64, y: 1150, w: 340, h: 92 },
      },
    },
    {
      id: "title1",
      type: "text",
      role: "headline",
      label: "Überschrift 1",
      font: {
        family: SANS,
        weight: 800,
        minSize: 52,
        maxSize: 84,
        lineHeight: 1.08,
      },
      color: "background",
      align: "left",
      vAlign: "top",
      maxLines: 3,
      maxChars: 70,
      example: "Handgemachte Keramik",
      guardrails: TEXT_RAILS,
      frames: {
        square: { x: 64, y: 640, w: 880, h: 220 },
        portrait: { x: 64, y: 860, w: 880, h: 240 },
        story: { x: 64, y: 1250, w: 900, h: 280 },
      },
    },
    {
      id: "text1",
      type: "text",
      role: "description",
      label: "Beschreibungstext 1",
      optional: true,
      multiline: true,
      font: {
        family: SANS,
        weight: 400,
        minSize: 24,
        maxSize: 32,
        lineHeight: 1.4,
      },
      color: "background",
      align: "left",
      vAlign: "top",
      maxLines: 3,
      maxChars: 140,
      example: "Jedes Stück ein Unikat – gedreht in unserer Werkstatt.",
      guardrails: TEXT_RAILS,
      frames: {
        square: { x: 64, y: 872, w: 720, h: 110 },
        portrait: { x: 64, y: 1112, w: 720, h: 120 },
        story: { x: 64, y: 1546, w: 760, h: 140 },
      },
    },
    {
      id: "text2",
      type: "text",
      role: "note",
      label: "Beschreibungstext 2",
      optional: true,
      font: {
        family: SANS,
        weight: 500,
        minSize: 20,
        maxSize: 26,
        lineHeight: 1.3,
      },
      color: "background",
      align: "left",
      vAlign: "center",
      maxLines: 1,
      maxChars: 60,
      example: "Nur solange der Vorrat reicht",
      guardrails: TEXT_RAILS,
      frames: {
        square: { x: 64, y: 988, w: 720, h: 50 },
        portrait: { x: 64, y: 1240, w: 720, h: 50 },
        story: { x: 64, y: 1698, w: 760, h: 56 },
      },
    },
    qr({
      square: { x: 920, y: 920, w: 100, h: 100 },
      portrait: { x: 920, y: 1180, w: 100, h: 100 },
      story: { x: 900, y: 1680, w: 120, h: 120 },
    }),
    logo({
      square: { x: 48, y: 48, w: 120, h: 120 },
      portrait: { x: 48, y: 48, w: 120, h: 120 },
      story: { x: 48, y: 64, w: 140, h: 140 },
    }),
  ],
};

/* ------------------------------------------------------------------ Galerie */

/** Photo in a generous passe-partout, centered serif title. */
const galerie: Template = {
  id: "galerie",
  name: "Galerie",
  hint: "Foto im Rahmen, ruhige Mitte",
  palettes: PALETTES,
  variants: [
    { id: "klassisch", name: "Klassisch", overrides: {} },
    {
      id: "rund",
      name: "Runde Ecken",
      overrides: { photo: { cornerRadius: 48 } },
    },
  ],
  slots: [
    {
      id: "bg",
      type: "background",
      fill: { type: "solid", role: "surface" },
      frames: FULL_FRAMES,
    },
    {
      id: "photo",
      type: "photo",
      cornerRadius: 8,
      guardrails: PHOTO_RAILS,
      frames: {
        square: { x: 64, y: 64, w: 952, h: 620 },
        portrait: { x: 64, y: 64, w: 952, h: 840 },
        story: { x: 64, y: 96, w: 952, h: 1180 },
      },
    },
    {
      id: "title2",
      type: "text",
      role: "highlight",
      label: "Überschrift 2",
      optional: true,
      font: {
        family: SANS,
        weight: 600,
        minSize: 22,
        maxSize: 26,
        lineHeight: 1.2,
        letterSpacing: 5,
        uppercase: true,
      },
      color: "accent",
      align: "center",
      vAlign: "center",
      maxLines: 1,
      maxChars: 30,
      example: "Neu eingetroffen",
      guardrails: TEXT_RAILS,
      frames: {
        square: { x: 104, y: 726, w: 872, h: 40 },
        portrait: { x: 104, y: 950, w: 872, h: 40 },
        story: { x: 104, y: 1330, w: 872, h: 44 },
      },
    },
    {
      id: "title1",
      type: "text",
      role: "headline",
      label: "Überschrift 1",
      font: {
        family: SERIF,
        weight: 600,
        minSize: 42,
        maxSize: 64,
        lineHeight: 1.15,
      },
      color: "text",
      align: "center",
      vAlign: "top",
      maxLines: 2,
      maxChars: 50,
      example: "Vase „Landliebe“",
      guardrails: TEXT_RAILS,
      frames: {
        square: { x: 104, y: 780, w: 872, h: 150 },
        portrait: { x: 104, y: 1004, w: 872, h: 160 },
        story: { x: 104, y: 1390, w: 872, h: 190 },
      },
    },
    {
      id: "text1",
      type: "text",
      role: "description",
      label: "Beschreibungstext 1",
      optional: true,
      multiline: true,
      font: {
        family: SANS,
        weight: 400,
        minSize: 22,
        maxSize: 28,
        lineHeight: 1.45,
      },
      color: "muted",
      align: "center",
      vAlign: "top",
      maxLines: 2,
      maxChars: 100,
      example:
        "Jedes Stück ein Unikat – gedreht und glasiert in unserer Werkstatt.",
      guardrails: TEXT_RAILS,
      frames: {
        square: { x: 160, y: 940, w: 760, h: 80 },
        portrait: { x: 160, y: 1174, w: 760, h: 90 },
        story: { x: 160, y: 1596, w: 760, h: 110 },
      },
    },
    {
      id: "text2",
      type: "text",
      role: "note",
      label: "Beschreibungstext 2",
      optional: true,
      font: {
        family: SANS,
        weight: 700,
        minSize: 24,
        maxSize: 34,
        lineHeight: 1.2,
      },
      color: "accent",
      align: "center",
      vAlign: "center",
      maxLines: 1,
      maxChars: 40,
      example: "39 €",
      guardrails: TEXT_RAILS,
      frames: {
        square: { x: 160, y: 1026, w: 760, h: 50 },
        portrait: { x: 160, y: 1270, w: 760, h: 56 },
        story: { x: 160, y: 1716, w: 760, h: 60 },
      },
    },
    qr({
      square: { x: 930, y: 950, w: 90, h: 90 },
      portrait: { x: 930, y: 1200, w: 90, h: 90 },
      story: { x: 920, y: 1740, w: 110, h: 110 },
    }),
    logo({
      square: { x: 56, y: 950, w: 88, h: 88 },
      portrait: { x: 56, y: 1200, w: 88, h: 88 },
      story: { x: 56, y: 1740, w: 108, h: 108 },
    }),
  ],
};

/* -------------------------------------------------------------------- Zitat */

/** Big centered serif quote — the only template that needs no photo at all. */
const zitat: Template = {
  id: "zitat",
  name: "Zitat",
  hint: "Nur Text, ganz groß – ohne Foto",
  palettes: PALETTES,
  variants: [
    { id: "klassisch", name: "Mit Zeichen", overrides: {} },
    { id: "pur", name: "Pur", overrides: { mark: { hidden: true } } },
  ],
  slots: [
    {
      id: "bg",
      type: "background",
      fill: { type: "solid", role: "background" },
      frames: FULL_FRAMES,
    },
    {
      id: "mark",
      type: "text",
      role: "decoration",
      label: "",
      fixed: true,
      font: {
        family: SERIF,
        weight: 900,
        minSize: 140,
        maxSize: 180,
        lineHeight: 1,
      },
      color: "accent",
      align: "center",
      vAlign: "center",
      maxLines: 1,
      example: "„",
      frames: {
        square: { x: 440, y: 96, w: 200, h: 170 },
        portrait: { x: 440, y: 140, w: 200, h: 190 },
        story: { x: 440, y: 260, w: 200, h: 210 },
      },
    },
    {
      id: "title1",
      type: "text",
      role: "headline",
      label: "Überschrift 1",
      multiline: true,
      font: {
        family: SERIF,
        weight: 500,
        minSize: 40,
        maxSize: 68,
        lineHeight: 1.25,
      },
      color: "text",
      align: "center",
      vAlign: "center",
      maxLines: 6,
      maxChars: 220,
      example:
        "Das Glück ist das einzige, das sich verdoppelt, wenn man es teilt.",
      guardrails: TEXT_RAILS,
      frames: {
        square: { x: 104, y: 290, w: 872, h: 440 },
        portrait: { x: 104, y: 370, w: 872, h: 540 },
        story: { x: 104, y: 520, w: 872, h: 740 },
      },
    },
    {
      id: "rule",
      type: "shape",
      shape: "rect",
      fill: { type: "solid", role: "accent" },
      cornerRadius: 3,
      frames: {
        square: { x: 505, y: 780, w: 70, h: 6 },
        portrait: { x: 505, y: 960, w: 70, h: 6 },
        story: { x: 505, y: 1320, w: 70, h: 6 },
      },
    },
    {
      id: "title2",
      type: "text",
      role: "highlight",
      label: "Überschrift 2",
      optional: true,
      font: {
        family: SANS,
        weight: 600,
        minSize: 22,
        maxSize: 28,
        lineHeight: 1.3,
        letterSpacing: 3,
        uppercase: true,
      },
      color: "muted",
      align: "center",
      vAlign: "top",
      maxLines: 1,
      maxChars: 40,
      example: "Albert Schweitzer",
      guardrails: TEXT_RAILS,
      frames: {
        square: { x: 190, y: 822, w: 700, h: 44 },
        portrait: { x: 190, y: 1002, w: 700, h: 44 },
        story: { x: 190, y: 1362, w: 700, h: 48 },
      },
    },
    {
      id: "text1",
      type: "text",
      role: "description",
      label: "Beschreibungstext 1",
      optional: true,
      multiline: true,
      font: {
        family: SANS,
        weight: 400,
        minSize: 22,
        maxSize: 28,
        lineHeight: 1.45,
      },
      color: "muted",
      align: "center",
      vAlign: "top",
      maxLines: 3,
      maxChars: 140,
      example: "Ein Gedanke, der uns durch die Woche trägt.",
      guardrails: TEXT_RAILS,
      frames: {
        square: { x: 160, y: 890, w: 760, h: 100 },
        portrait: { x: 160, y: 1070, w: 760, h: 110 },
        story: { x: 160, y: 1440, w: 760, h: 130 },
      },
    },
    {
      id: "text2",
      type: "text",
      role: "note",
      label: "Beschreibungstext 2",
      optional: true,
      font: {
        family: SANS,
        weight: 500,
        minSize: 20,
        maxSize: 26,
        lineHeight: 1.3,
      },
      color: "muted",
      align: "center",
      vAlign: "center",
      maxLines: 1,
      maxChars: 60,
      example: "Schön, dass du da bist",
      guardrails: TEXT_RAILS,
      frames: {
        square: { x: 160, y: 996, w: 760, h: 44 },
        portrait: { x: 160, y: 1190, w: 760, h: 44 },
        story: { x: 160, y: 1584, w: 760, h: 50 },
      },
    },
    qr({
      square: { x: 944, y: 976, w: 80, h: 80 },
      portrait: { x: 944, y: 1210, w: 80, h: 80 },
      story: { x: 924, y: 1700, w: 100, h: 100 },
    }),
    logo({
      square: { x: 56, y: 976, w: 80, h: 80 },
      portrait: { x: 56, y: 1210, w: 80, h: 80 },
      story: { x: 56, y: 1700, w: 100, h: 100 },
    }),
  ],
};

/* -------------------------------------------------------------------- Notiz */

/** Card look, text first: tips, opening hours, announcements. */
const notiz: Template = {
  id: "notiz",
  name: "Notiz",
  hint: "Textkarte für Tipps, Zeiten, Hinweise",
  palettes: PALETTES,
  variants: [
    { id: "weich", name: "Abgerundet", overrides: {} },
    { id: "kantig", name: "Kantig", overrides: { card: { cornerRadius: 0 } } },
  ],
  slots: [
    {
      id: "bg",
      type: "background",
      fill: { type: "solid", role: "background" },
      frames: FULL_FRAMES,
    },
    {
      id: "card",
      type: "shape",
      shape: "rect",
      fill: { type: "solid", role: "surface" },
      cornerRadius: 40,
      frames: {
        square: { x: 64, y: 120, w: 952, h: 840 },
        portrait: { x: 64, y: 140, w: 952, h: 1070 },
        story: { x: 64, y: 240, w: 952, h: 1440 },
      },
    },
    {
      id: "title2",
      type: "text",
      role: "highlight",
      label: "Überschrift 2",
      optional: true,
      font: {
        family: SANS,
        weight: 700,
        minSize: 22,
        maxSize: 26,
        lineHeight: 1.2,
        letterSpacing: 3,
        uppercase: true,
      },
      color: "textOnAccent",
      align: "left",
      vAlign: "center",
      maxLines: 1,
      maxChars: 24,
      badge: {
        fill: { type: "solid", role: "accent" },
        paddingX: 26,
        paddingY: 14,
        cornerRadius: 999,
      },
      example: "Tipp des Tages",
      guardrails: TEXT_RAILS,
      frames: {
        square: { x: 154, y: 190, w: 500, h: 50 },
        portrait: { x: 154, y: 214, w: 500, h: 50 },
        story: { x: 154, y: 320, w: 500, h: 54 },
      },
    },
    {
      id: "title1",
      type: "text",
      role: "headline",
      label: "Überschrift 1",
      font: {
        family: SANS,
        weight: 700,
        minSize: 34,
        maxSize: 52,
        lineHeight: 1.18,
      },
      color: "text",
      align: "left",
      vAlign: "top",
      maxLines: 3,
      maxChars: 80,
      example: "So bleibt dein Brot länger frisch",
      guardrails: TEXT_RAILS,
      frames: {
        square: { x: 128, y: 290, w: 824, h: 190 },
        portrait: { x: 128, y: 320, w: 824, h: 210 },
        story: { x: 128, y: 430, w: 824, h: 250 },
      },
    },
    {
      id: "text1",
      type: "text",
      role: "description",
      label: "Beschreibungstext 1",
      optional: true,
      multiline: true,
      font: {
        family: SANS,
        weight: 400,
        minSize: 26,
        maxSize: 32,
        lineHeight: 1.45,
      },
      color: "muted",
      align: "left",
      vAlign: "top",
      maxLines: 7,
      maxChars: 320,
      example:
        "Bewahre Brot nie im Kühlschrank auf – dort wird es schneller alt. Ein Brotkasten aus Ton hält die Kruste knusprig.",
      guardrails: TEXT_RAILS,
      frames: {
        square: { x: 128, y: 500, w: 824, h: 300 },
        portrait: { x: 128, y: 550, w: 824, h: 480 },
        story: { x: 128, y: 700, w: 824, h: 700 },
      },
    },
    {
      id: "text2",
      type: "text",
      role: "note",
      label: "Beschreibungstext 2",
      optional: true,
      font: {
        family: SANS,
        weight: 500,
        minSize: 20,
        maxSize: 26,
        lineHeight: 1.3,
      },
      color: "accent",
      align: "left",
      vAlign: "center",
      maxLines: 1,
      maxChars: 60,
      example: "Mehr Tipps jede Woche hier",
      guardrails: TEXT_RAILS,
      frames: {
        square: { x: 128, y: 812, w: 600, h: 50 },
        portrait: { x: 128, y: 1046, w: 600, h: 50 },
        story: { x: 128, y: 1416, w: 700, h: 56 },
      },
    },
    qr({
      square: { x: 856, y: 832, w: 96, h: 96 },
      portrait: { x: 856, y: 1082, w: 96, h: 96 },
      story: { x: 832, y: 1528, w: 120, h: 120 },
    }),
    logo({
      square: { x: 128, y: 880, w: 72, h: 72 },
      portrait: { x: 128, y: 1106, w: 72, h: 72 },
      story: { x: 128, y: 1528, w: 100, h: 100 },
    }),
  ],
};

/* --------------------------------------------------------------- Steckbrief */

/** Three fact columns (fixed caption + editable value) — the dog CV extras. */
function factColumns(): Slot[] {
  const columns = [
    {
      key: "dog:age",
      caption: "Alter",
      label: "Alter",
      example: "3 Jahre",
      x: 64,
    },
    {
      key: "dog:breed",
      caption: "Rasse",
      label: "Rasse",
      example: "Mischling",
      x: 381,
    },
    {
      key: "dog:sex",
      caption: "Geschlecht",
      label: "Geschlecht",
      example: "Rüde",
      x: 698,
    },
  ];
  return columns.flatMap((column): Slot[] => [
    {
      id: `${column.key}-caption`,
      type: "text",
      role: "caption",
      label: "",
      fixed: true,
      showWith: column.key,
      font: {
        family: SANS,
        weight: 600,
        minSize: 18,
        maxSize: 21,
        lineHeight: 1.2,
        letterSpacing: 2,
        uppercase: true,
      },
      color: "muted",
      align: "left",
      vAlign: "bottom",
      maxLines: 1,
      example: column.caption,
      frames: {
        square: { x: column.x, y: 744, w: 280, h: 30 },
        portrait: { x: column.x, y: 914, w: 280, h: 30 },
        story: { x: column.x, y: 1258, w: 280, h: 34 },
      },
    },
    {
      id: column.key,
      type: "text",
      role: "fact",
      label: column.label,
      optional: true,
      font: {
        family: SANS,
        weight: 700,
        minSize: 24,
        maxSize: 32,
        lineHeight: 1.2,
      },
      color: "text",
      align: "left",
      vAlign: "top",
      maxLines: 1,
      maxChars: 18,
      example: column.example,
      guardrails: TEXT_RAILS,
      frames: {
        square: { x: column.x, y: 780, w: 280, h: 46 },
        portrait: { x: column.x, y: 950, w: 280, h: 46 },
        story: { x: column.x, y: 1298, w: 280, h: 50 },
      },
    },
  ]);
}

/** The shelter-dog CV: photo, name, fact columns, story. */
const steckbrief: Template = {
  id: "steckbrief",
  name: "Steckbrief",
  hint: "Für Hunde: Foto, Name, Alter, Rasse …",
  palettes: PALETTES,
  variants: [
    { id: "weich", name: "Abgerundet", overrides: {} },
    { id: "kantig", name: "Kantig", overrides: { panel: { cornerRadius: 0 } } },
  ],
  slots: [
    {
      id: "bg",
      type: "background",
      fill: { type: "solid", role: "background" },
      frames: FULL_FRAMES,
    },
    {
      id: "photo",
      type: "photo",
      guardrails: PHOTO_RAILS,
      frames: {
        square: { x: 0, y: 0, w: 1080, h: 560 },
        portrait: { x: 0, y: 0, w: 1080, h: 720 },
        story: { x: 0, y: 0, w: 1080, h: 1040 },
      },
    },
    {
      id: "panel",
      type: "shape",
      shape: "rect",
      fill: { type: "solid", role: "surface" },
      cornerRadius: 48,
      frames: {
        square: { x: 0, y: 520, w: 1080, h: 560 },
        portrait: { x: 0, y: 680, w: 1080, h: 670 },
        story: { x: 0, y: 1000, w: 1080, h: 920 },
      },
    },
    {
      id: "title2",
      type: "text",
      role: "highlight",
      label: "Überschrift 2",
      optional: true,
      font: {
        family: SANS,
        weight: 700,
        minSize: 20,
        maxSize: 23,
        lineHeight: 1.2,
        letterSpacing: 4,
        uppercase: true,
      },
      color: "accent",
      align: "left",
      vAlign: "bottom",
      maxLines: 1,
      maxChars: 34,
      example: "Ich suche ein Zuhause",
      guardrails: TEXT_RAILS,
      frames: {
        square: { x: 64, y: 562, w: 850, h: 34 },
        portrait: { x: 64, y: 722, w: 850, h: 34 },
        story: { x: 64, y: 1044, w: 850, h: 38 },
      },
    },
    {
      id: "title1",
      type: "text",
      role: "headline",
      label: "Überschrift 1",
      font: {
        family: SERIF,
        weight: 700,
        minSize: 56,
        maxSize: 84,
        lineHeight: 1.05,
      },
      color: "text",
      align: "left",
      vAlign: "top",
      maxLines: 1,
      maxChars: 20,
      example: "Bello",
      guardrails: TEXT_RAILS,
      frames: {
        square: { x: 64, y: 606, w: 850, h: 108 },
        portrait: { x: 64, y: 766, w: 850, h: 118 },
        story: { x: 64, y: 1090, w: 850, h: 138 },
      },
    },
    ...factColumns(),
    {
      id: "dog:traits",
      type: "text",
      role: "fact",
      label: "Charakter (z. B. verspielt · lieb)",
      optional: true,
      font: {
        family: SANS,
        weight: 600,
        minSize: 24,
        maxSize: 29,
        lineHeight: 1.3,
      },
      color: "accent",
      align: "left",
      vAlign: "center",
      maxLines: 1,
      maxChars: 50,
      example: "verspielt · kinderlieb · leinenführig",
      guardrails: TEXT_RAILS,
      frames: {
        square: { x: 64, y: 848, w: 850, h: 42 },
        portrait: { x: 64, y: 1020, w: 850, h: 42 },
        story: { x: 64, y: 1372, w: 850, h: 46 },
      },
    },
    {
      id: "text1",
      type: "text",
      role: "description",
      label: "Beschreibungstext 1",
      optional: true,
      multiline: true,
      font: {
        family: SANS,
        weight: 400,
        minSize: 22,
        maxSize: 27,
        lineHeight: 1.42,
      },
      color: "muted",
      align: "left",
      vAlign: "top",
      maxLines: 4,
      maxChars: 220,
      example:
        "Ich bin ein fröhlicher Kerl, der Menschen liebt und gern Neues lernt. Ein Garten wäre mein großer Traum!",
      guardrails: TEXT_RAILS,
      frames: {
        square: { x: 64, y: 910, w: 700, h: 110 },
        portrait: { x: 64, y: 1082, w: 700, h: 190 },
        story: { x: 64, y: 1440, w: 690, h: 300 },
      },
    },
    {
      id: "text2",
      type: "text",
      role: "note",
      label: "Beschreibungstext 2",
      optional: true,
      font: {
        family: SANS,
        weight: 500,
        minSize: 20,
        maxSize: 25,
        lineHeight: 1.3,
      },
      color: "muted",
      align: "left",
      vAlign: "center",
      maxLines: 1,
      maxChars: 60,
      example: "Lern mich kennen – scann den Code!",
      guardrails: TEXT_RAILS,
      frames: {
        square: { x: 64, y: 1028, w: 700, h: 44 },
        portrait: { x: 64, y: 1280, w: 700, h: 50 },
        story: { x: 64, y: 1750, w: 690, h: 56 },
      },
    },
    qr({
      square: { x: 866, y: 906, w: 120, h: 120 },
      portrait: { x: 866, y: 1082, w: 120, h: 120 },
      story: { x: 850, y: 1460, w: 140, h: 140 },
    }),
    logo({
      square: { x: 48, y: 48, w: 120, h: 120 },
      portrait: { x: 48, y: 48, w: 120, h: 120 },
      story: { x: 48, y: 64, w: 140, h: 140 },
    }),
  ],
};

export const singleTemplates: Template[] = [
  klassik,
  vollbild,
  galerie,
  notiz,
  zitat,
  steckbrief,
];
