/**
 * Template set "Team & Hinweise": practical everyday posts — introducing a
 * (new) team member, opening hours, and a friendly "we're closed" notice.
 * Text-first where possible so they look finished without uploads.
 */
import type { Palette, Template } from "../engine/types";
import {
  BADGE_RAILS,
  FULL_FRAMES,
  LOGO_RAILS,
  QR_RAILS,
  SANS,
  SERIF,
  TEXT_RAILS,
} from "./shared";

const TEAM_PALETTES: Palette[] = [
  {
    id: "petrol",
    name: "Petrol",
    colors: {
      background: "#e8f0f0",
      surface: "#ffffff",
      accent: "#2f6f6a",
      text: "#1a2b29",
      textOnAccent: "#ecf7f5",
      muted: "#6f8683",
    },
  },
  {
    id: "apricot",
    name: "Aprikose",
    colors: {
      background: "#fbf0e5",
      surface: "#ffffff",
      accent: "#d07a3f",
      text: "#2e2013",
      textOnAccent: "#fff5ec",
      muted: "#9a8168",
    },
  },
  {
    id: "graphit",
    name: "Graphit (dunkel)",
    colors: {
      background: "#26282c",
      surface: "#32353b",
      accent: "#e2b954",
      text: "#f0efe9",
      textOnAccent: "#2a2109",
      muted: "#a0a4ad",
    },
  },
  {
    id: "linde",
    name: "Linde",
    colors: {
      background: "#eef2e6",
      surface: "#ffffff",
      accent: "#5f7f3f",
      text: "#232b18",
      textOnAccent: "#f4f9ec",
      muted: "#83906f",
    },
  },
  {
    id: "marine",
    name: "Marine",
    colors: {
      background: "#e7edf6",
      surface: "#ffffff",
      accent: "#274a7c",
      text: "#16233a",
      textOnAccent: "#edf3fc",
      muted: "#6f7f96",
    },
  },
];

/** Photo top, white panel: introduce a (new) team member. */
const teamVorstellung: Template = {
  id: "team-vorstellung",
  name: "Neu im Team",
  category: "team",
  palettes: TEAM_PALETTES,
  variants: [
    { id: "weich", name: "Abgerundet", overrides: {} },
    { id: "kantig", name: "Kantig", overrides: { panel: { cornerRadius: 0 } } },
  ],
  slots: [
    {
      id: "bg",
      type: "background",
      fill: { type: "solid", role: "background" },
      frames: FULL_FRAMES,
    },
    {
      id: "photo",
      type: "photo",
      frames: {
        square: { x: 0, y: 0, w: 1080, h: 560 },
        portrait: { x: 0, y: 0, w: 1080, h: 720 },
        story: { x: 0, y: 0, w: 1080, h: 1040 },
      },
    },
    {
      id: "panel",
      type: "shape",
      shape: "rect",
      fill: { type: "solid", role: "surface" },
      cornerRadius: 48,
      frames: {
        square: { x: 0, y: 520, w: 1080, h: 560 },
        portrait: { x: 0, y: 680, w: 1080, h: 670 },
        story: { x: 0, y: 1000, w: 1080, h: 920 },
      },
    },
    {
      id: "eyebrow",
      type: "text",
      role: "eyebrow",
      label: "Kleine Zeile (z. B. Neu im Team)",
      font: {
        family: SANS,
        weight: 700,
        minSize: 22,
        maxSize: 26,
        lineHeight: 1.2,
        letterSpacing: 2,
        uppercase: true,
      },
      color: "textOnAccent",
      align: "left",
      vAlign: "center",
      maxLines: 1,
      maxChars: 24,
      badge: {
        fill: { type: "solid", role: "accent" },
        paddingX: 26,
        paddingY: 13,
        cornerRadius: 999,
      },
      example: "Neu im Team",
      guardrails: BADGE_RAILS,
      frames: {
        square: { x: 64, y: 556, w: 520, h: 48 },
        portrait: { x: 64, y: 716, w: 520, h: 48 },
        story: { x: 64, y: 1036, w: 520, h: 52 },
      },
    },
    {
      id: "name",
      type: "text",
      role: "name",
      label: "Name",
      font: {
        family: SERIF,
        weight: 650,
        minSize: 52,
        maxSize: 80,
        lineHeight: 1.05,
      },
      color: "text",
      align: "left",
      vAlign: "top",
      maxLines: 1,
      maxChars: 24,
      example: "Maria",
      guardrails: TEXT_RAILS,
      frames: {
        square: { x: 64, y: 632, w: 850, h: 100 },
        portrait: { x: 64, y: 792, w: 850, h: 110 },
        story: { x: 64, y: 1112, w: 850, h: 130 },
      },
    },
    {
      id: "role",
      type: "text",
      role: "role",
      label: "Was macht sie/er?",
      font: {
        family: SANS,
        weight: 600,
        minSize: 26,
        maxSize: 32,
        lineHeight: 1.25,
      },
      color: "accent",
      align: "left",
      vAlign: "center",
      maxLines: 1,
      maxChars: 45,
      example: "Unsere neue Hundetrainerin",
      guardrails: TEXT_RAILS,
      frames: {
        square: { x: 64, y: 740, w: 850, h: 44 },
        portrait: { x: 64, y: 910, w: 850, h: 44 },
        story: { x: 64, y: 1250, w: 850, h: 48 },
      },
    },
    {
      id: "about",
      type: "text",
      role: "about",
      label: "Ein paar Sätze",
      optional: true,
      multiline: true,
      font: {
        family: SANS,
        weight: 400,
        minSize: 22,
        maxSize: 27,
        lineHeight: 1.42,
      },
      color: "muted",
      align: "left",
      vAlign: "top",
      maxLines: 5,
      maxChars: 240,
      example:
        "Maria verstärkt ab sofort unser Team – mit viel Geduld, Herz und einer Tasche voller Leckerlis. Sag ihr gern Hallo!",
      guardrails: TEXT_RAILS,
      frames: {
        square: { x: 64, y: 804, w: 700, h: 210 },
        portrait: { x: 64, y: 974, w: 700, h: 250 },
        story: { x: 64, y: 1324, w: 690, h: 330 },
      },
    },
    {
      id: "qr",
      type: "qr",
      optional: true,
      guardrails: QR_RAILS,
      frames: {
        square: { x: 866, y: 896, w: 120, h: 120 },
        portrait: { x: 866, y: 1086, w: 120, h: 120 },
        story: { x: 850, y: 1470, w: 140, h: 140 },
      },
    },
    {
      id: "logo",
      type: "logo",
      optional: true,
      guardrails: LOGO_RAILS,
      frames: {
        square: { x: 48, y: 48, w: 120, h: 120 },
        portrait: { x: 48, y: 48, w: 120, h: 120 },
        story: { x: 48, y: 64, w: 140, h: 140 },
      },
    },
  ],
};

/** Opening hours on a friendly card — one line per day, newlines respected. */
const oeffnungszeiten: Template = {
  id: "oeffnungszeiten",
  name: "Öffnungszeiten",
  category: "team",
  palettes: TEAM_PALETTES,
  variants: [
    { id: "weich", name: "Abgerundet", overrides: {} },
    { id: "kantig", name: "Kantig", overrides: { card: { cornerRadius: 0 } } },
  ],
  slots: [
    {
      id: "bg",
      type: "background",
      fill: { type: "solid", role: "background" },
      frames: FULL_FRAMES,
    },
    {
      id: "card",
      type: "shape",
      shape: "rect",
      fill: { type: "solid", role: "surface" },
      cornerRadius: 40,
      frames: {
        square: { x: 64, y: 120, w: 952, h: 840 },
        portrait: { x: 64, y: 140, w: 952, h: 1070 },
        story: { x: 64, y: 240, w: 952, h: 1440 },
      },
    },
    {
      id: "eyebrow",
      type: "text",
      role: "eyebrow",
      label: "Kleine Zeile oben",
      optional: true,
      font: {
        family: SANS,
        weight: 700,
        minSize: 22,
        maxSize: 26,
        lineHeight: 1.2,
        letterSpacing: 4,
        uppercase: true,
      },
      color: "accent",
      align: "center",
      vAlign: "center",
      maxLines: 1,
      maxChars: 28,
      example: "Gut zu wissen",
      guardrails: TEXT_RAILS,
      frames: {
        square: { x: 104, y: 190, w: 872, h: 40 },
        portrait: { x: 104, y: 214, w: 872, h: 40 },
        story: { x: 104, y: 320, w: 872, h: 44 },
      },
    },
    {
      id: "headline",
      type: "text",
      role: "headline",
      label: "Überschrift",
      font: {
        family: SERIF,
        weight: 600,
        minSize: 42,
        maxSize: 64,
        lineHeight: 1.15,
      },
      color: "text",
      align: "center",
      vAlign: "center",
      maxLines: 2,
      maxChars: 50,
      example: "Unsere Öffnungszeiten",
      guardrails: TEXT_RAILS,
      frames: {
        square: { x: 128, y: 250, w: 824, h: 140 },
        portrait: { x: 128, y: 280, w: 824, h: 150 },
        story: { x: 128, y: 390, w: 824, h: 180 },
      },
    },
    {
      id: "times",
      type: "text",
      role: "body",
      label: "Deine Zeiten (eine Zeile pro Tag)",
      multiline: true,
      font: {
        family: SANS,
        weight: 500,
        minSize: 28,
        maxSize: 40,
        lineHeight: 1.55,
      },
      color: "text",
      align: "center",
      vAlign: "center",
      maxLines: 7,
      maxChars: 220,
      example: "Mo – Fr: 9 bis 18 Uhr\nSa: 9 bis 14 Uhr\nSo: Ruhetag",
      guardrails: TEXT_RAILS,
      frames: {
        square: { x: 128, y: 420, w: 824, h: 320 },
        portrait: { x: 128, y: 470, w: 824, h: 430 },
        story: { x: 128, y: 620, w: 824, h: 560 },
      },
    },
    {
      id: "note",
      type: "text",
      role: "description",
      label: "Zusatz (optional)",
      optional: true,
      font: {
        family: SANS,
        weight: 400,
        minSize: 22,
        maxSize: 27,
        lineHeight: 1.4,
      },
      color: "muted",
      align: "center",
      vAlign: "top",
      maxLines: 2,
      maxChars: 90,
      example: "An Feiertagen bleibt der Laden geschlossen.",
      guardrails: TEXT_RAILS,
      frames: {
        square: { x: 144, y: 764, w: 792, h: 64 },
        portrait: { x: 144, y: 940, w: 792, h: 80 },
        story: { x: 144, y: 1240, w: 792, h: 100 },
      },
    },
    {
      id: "qr",
      type: "qr",
      optional: true,
      guardrails: QR_RAILS,
      frames: {
        square: { x: 856, y: 832, w: 96, h: 96 },
        portrait: { x: 856, y: 1082, w: 96, h: 96 },
        story: { x: 832, y: 1528, w: 120, h: 120 },
      },
    },
    {
      id: "logo",
      type: "logo",
      optional: true,
      guardrails: LOGO_RAILS,
      frames: {
        square: { x: 128, y: 840, w: 90, h: 90 },
        portrait: { x: 128, y: 1090, w: 90, h: 90 },
        story: { x: 128, y: 1540, w: 110, h: 110 },
      },
    },
  ],
};

/** Friendly "we're on a break" notice on a full accent background. */
const pauseHinweis: Template = {
  id: "pause-hinweis",
  name: "Wir machen Pause",
  category: "team",
  palettes: TEAM_PALETTES,
  variants: [
    { id: "flaeche", name: "Einfarbig", overrides: {} },
    {
      id: "verlauf",
      name: "Verlauf",
      overrides: {
        bg: {
          fill: {
            type: "linear-gradient",
            from: "accent",
            to: "text",
            angle: 24,
          },
        },
      },
    },
  ],
  slots: [
    {
      id: "bg",
      type: "background",
      fill: { type: "solid", role: "accent" },
      frames: FULL_FRAMES,
    },
    {
      id: "logo",
      type: "logo",
      optional: true,
      guardrails: LOGO_RAILS,
      frames: {
        square: { x: 490, y: 64, w: 100, h: 100 },
        portrait: { x: 490, y: 80, w: 100, h: 100 },
        story: { x: 480, y: 140, w: 120, h: 120 },
      },
    },
    {
      id: "eyebrow",
      type: "text",
      role: "eyebrow",
      label: "Kleine Zeile oben",
      optional: true,
      font: {
        family: SANS,
        weight: 700,
        minSize: 22,
        maxSize: 28,
        lineHeight: 1.2,
        letterSpacing: 4,
        uppercase: true,
      },
      color: "textOnAccent",
      align: "center",
      vAlign: "center",
      maxLines: 1,
      maxChars: 30,
      example: "Kurze Auszeit",
      guardrails: TEXT_RAILS,
      frames: {
        square: { x: 140, y: 200, w: 800, h: 44 },
        portrait: { x: 140, y: 250, w: 800, h: 44 },
        story: { x: 140, y: 380, w: 800, h: 48 },
      },
    },
    {
      id: "headline",
      type: "text",
      role: "headline",
      label: "Deine Nachricht",
      multiline: true,
      font: {
        family: SERIF,
        weight: 600,
        minSize: 46,
        maxSize: 74,
        lineHeight: 1.15,
      },
      color: "textOnAccent",
      align: "center",
      vAlign: "center",
      maxLines: 3,
      maxChars: 80,
      example: "Wir machen kurz Pause",
      guardrails: TEXT_RAILS,
      frames: {
        square: { x: 84, y: 270, w: 912, h: 330 },
        portrait: { x: 84, y: 340, w: 912, h: 380 },
        story: { x: 84, y: 500, w: 912, h: 460 },
      },
    },
    {
      id: "datebadge",
      type: "text",
      role: "date",
      label: "Von wann bis wann?",
      font: {
        family: SANS,
        weight: 700,
        minSize: 26,
        maxSize: 36,
        lineHeight: 1.15,
      },
      color: "text",
      align: "center",
      vAlign: "center",
      maxLines: 1,
      maxChars: 40,
      badge: {
        fill: { type: "solid", role: "surface" },
        paddingX: 34,
        paddingY: 18,
        cornerRadius: 999,
      },
      example: "24. Dezember bis 6. Januar",
      guardrails: BADGE_RAILS,
      frames: {
        square: { x: 240, y: 650, w: 600, h: 90 },
        portrait: { x: 240, y: 790, w: 600, h: 90 },
        story: { x: 220, y: 1030, w: 640, h: 100 },
      },
    },
    {
      id: "note",
      type: "text",
      role: "description",
      label: "Zusatz (optional)",
      optional: true,
      font: {
        family: SANS,
        weight: 500,
        minSize: 24,
        maxSize: 30,
        lineHeight: 1.4,
      },
      color: "textOnAccent",
      align: "center",
      vAlign: "top",
      maxLines: 2,
      maxChars: 100,
      example: "Ab dem 7. Januar sind wir wieder für euch da!",
      guardrails: TEXT_RAILS,
      frames: {
        square: { x: 144, y: 780, w: 792, h: 90 },
        portrait: { x: 144, y: 930, w: 792, h: 100 },
        story: { x: 144, y: 1190, w: 792, h: 120 },
      },
    },
    {
      id: "qr",
      type: "qr",
      optional: true,
      guardrails: QR_RAILS,
      frames: {
        square: { x: 492, y: 908, w: 96, h: 96 },
        portrait: { x: 492, y: 1090, w: 96, h: 96 },
        story: { x: 480, y: 1420, w: 120, h: 120 },
      },
    },
  ],
};

export const teamTemplates: Template[] = [
  teamVorstellung,
  oeffnungszeiten,
  pauseHinweis,
];
